### ISSUE TITLE
Portable package for x64 win

### ISSUE THREAD

**Issue by hezral** [wexond/browser-base#104]
### Expected behavior
Please provide a zip file instead of an EXE file

### Actual behavior
All data should be saved within app directory

### Specifications
* Version: 
* OS:

**Comment by sentialx** [comment]
Hi, thanks for issue. We will try to configure `electron-builder` to also include the zip file as you mentioned.

**Comment by hezral** [comment]
Hi, any chance to get this? still only win32 zip file is available in the release page
