### ISSUE TITLE
AppImage of 1.0.0-beta-1 does not start

### ISSUE THREAD

**Issue by Kilian** [wexond/browser-base#112]
### Expected behavior
Application launches when opened

### Actual behavior
Application does not launch, with the following output:
```
[kilian:~]$ ./wexond-1.0.0-beta.1-x86_64.AppImage 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_wexondJXMDmM/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```

### Steps to reproduce the problem
Start the AppImage

### Specifications
* Version: Appimage x64
* OS: Ubuntu 16.04

**Comment by Kilian** [comment]
The .deb works, but does not have the correct icon (separate issue)

**Comment by sentialx** [comment]
Thanks for your issue! I will check electron-builder.
