### ISSUE TITLE
What should be in a new tab page?

### ISSUE THREAD

**Issue by sentialx** [wexond/browser-base#12]
What should be in a new tab page? Please give me your suggestions below. I'm wondering if add bookmarks cards or recently visited websites or something different.

**Comment by doreminiature** [comment]
Obviously most visited pages after user had some time with a browser. By default (first visit) most useful resources outh there. Ability to manually add, organize, group tabs(webpages) by topic will be nice.

**Comment by doreminiature** [comment]
Really quick mock: [https://i.imgur.com/uDUlbmO.png](https://i.imgur.com/uDUlbmO.png)
Btw, greetings from miniature web browser. Check your mail, I wrote you a mail. (:

**Comment by sentialx** [comment]
Thank you very much for your concept :) I will check my mail :)
