### ISSUE TITLE
theme-color doesn't work

### ISSUE THREAD

**Issue by ameoverflow** [wexond/browser-base#122]
When opening site with theme-color, toolbar stays white, when in 0.2.0 it changed color

**Comment by sentialx** [comment]
Okay, I think Wexond could change its selected tab color to the given `theme-color`, but only if the color will be dark enough. What do you think about it?

**Comment by ameoverflow** [comment]
No

**Comment by sentialx** [comment]
Could you be more precise?

**Comment by davidraywilson** [comment]
I like your idea @sentialx. I think it would be a clean implementation of the theme-color.
