### ISSUE TITLE
HTML files support

### ISSUE THREAD

**Issue by ameoverflow** [wexond/browser-base#123]
I'd like to see HTML local files support and other multimedia files like in Chrome

**Comment by sentialx** [comment]
I'm marking this as a bug, since it's not the expected behavior, will fix.

**Comment by sentialx** [comment]
Do you have any steps to reproduce this bug? I can't reproduce it, local HTML files are opening properly.

**Comment by AhmedMostafa16** [comment]
@Sential , you will find the answer here. 

https://electronjs.org/docs

**Comment by sentialx** [comment]
I'm asking for steps to reproduce this bug, not docs to electron...
