### ISSUE TITLE
blocking submit to newsletter

### ISSUE THREAD

**Issue by cztomsik** [wexond/browser-base#126]
Hey, how hard it would be to implement "submit to newsletter" blocking?

**Comment by sentialx** [comment]
Hi, we don't make blocking lists, but perhaps there is a list for uBlock Origin for blocking these popups.

**Comment by cztomsik** [comment]
No it would work for all pages, I mean it's really, really annoying when you scroll through the page (just to see if it's about what you're searching for) and then there's modal with submit to our newsletter and sometimes it will even show "before you go" over it, which is absolutely nuts.

Or maybe there could be something much much easier - like simple switch which would forbid access of mouse position and maybe scroll events? That would resolve this as well.

**Comment by sentialx** [comment]
Closing since I'm not the creator of AdBlock Plus nor uBlock Origin blocking lists.
