### ISSUE TITLE
Always-on-top Support

### ISSUE THREAD

**Issue by skoshy** [wexond/browser-base#129]
**Is your feature request related to a problem? Please describe.**
When watching a YouTube video or keeping a recipe open, I'd like the window to stay on top of other windows currently being shown.

**Describe the solution you'd like**
A menu-bar toggle for a window to "pin" it or make it be always-on-top

**Describe alternatives you've considered**
No other alternatives

**Comment by sentialx** [comment]
Thanks for opening an issue! Of course we can implement the always on top feature and we will.

**Comment by sentialx** [comment]
@skoshy Sorry for the delay. Your suggested feature should be in the next update,
