### ISSUE TITLE
Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by ceo0x** [wexond/browser-base#130]
I have this issue.

Im running it on OS X , using 2 terminals .. one to run "yarn watch" and other with "yarn start" 
Problem happens when you close all tabs

(node:3564) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get-tab-by-web-contents-id listeners added. Use emitter.setMaxListeners() to increase limit
(node:3564) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get-tab-by-web-contents-id listeners added. Use emitter.setMaxListeners() to increase limit
(node:3564) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get-tab-by-web-contents-id listeners added. Use emitter.setMaxListeners() to increase limit
(node:3564) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get-tab-by-web-contents-id listeners added. Use emitter.setMaxListeners() to increase limit
(node:3564) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get-tab-by-web-contents-id listeners added. Use emitter.setMaxListeners() to increase limit
[3598:0916/133543.638399:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.
(node:3564) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get-tab-by-web-contents-id listeners added. Use emitter.setMaxListeners() to increase limit
(node:3564) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 get-tab-by-web-contents-id listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by xnerhu** [comment]
Thanks for your issue! We will check it.

**Comment by sentialx** [comment]
This is not a bug. These logs are just warnings that perhaps there is too much event listeners. This can be omitted by just simply adding `ipcMain.setMaxListeners(0)`. Closing.

**Comment by ceo0x** [comment]
Well if you try to reproduce it you will notice its not a warning message only, tabs stop working and i cant browse to a new url .

Anyway , i am using the beta source now and it seems to be working fine
