### ISSUE TITLE
Settings and extensions not showing.

### ISSUE THREAD

**Issue by HardReposter** [wexond/browser-base#131]
When I opened Wexond for the first time, I immediately wanted to install the µblock extension. I clicked on the little hamburger menu button on the top right to open the menu, I clicked on the Extensions tab but nothing showed up and it was completely empty. Then I went to the Settings tab but that was also completely blank.

I already reinstalled Wexond to see if that had any effect and I also tried running Wexond with administrator privileges. Wexond was installed in AppData > Local > Programs > wexond.

![schermopname 14](https://user-images.githubusercontent.com/35396268/46310350-5fb62c80-c5bf-11e8-8d07-127457777b4e.png)
![schermopname 15](https://user-images.githubusercontent.com/35396268/46310361-647ae080-c5bf-11e8-9698-d7c398051b1a.png)

 OS: Windows 10 version 1803 (build 17134)
 Wexond version: 1.0.0-beta.1

**Comment by sentialx** [comment]
The version 1.0.0-beta.1 doesn't have extensions system, but it's in the latest commit. You can try to build Wexond from source code and extract uBlock Origin in `~/.wexond/extensions` directory.
