### ISSUE TITLE
Bug after upgrading to electron 3.0.0

### ISSUE THREAD

**Issue by ramanamatya** [wexond/browser-base#132]
**Describe the bug**
- After upgrading it to 3.0.0 the webview is blank after typing the url.

**To Reproduce**
1. Type Url
2. webview is blank

**Expected behavior**
- Webpage should be loaded

**Screenshots**
<img width="1433" alt="screen shot 2018-10-09 at 4 09 54 pm" src="https://user-images.githubusercontent.com/4321549/46663444-d1a0fe00-cbdd-11e8-8cb4-bb7827c133bd.png">

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser: Chrome

**Additional context**

**Comment by sentialx** [comment]
This is an Electron bug, because of rewriting to OOPIF architecture in <webview>. At the moment don't upgrade to 3.0.x.

**Comment by fanvyr** [comment]
Is there a best practice to enable 2 versions of electron in MacOS? Need to run electron 3 too..

**Comment by sentialx** [comment]
I have no idea what you are trying to achieve.
