### ISSUE TITLE
Cut more releases more frequently..

### ISSUE THREAD

**Issue by InputNeuron** [wexond/browser-base#133]
Hey guys.. really hoping you're successful.

My advice is to cut more releases more frequently to better involve the community. 

At least 1x per week.  Lots of people depend on just basic binaries.  This way you can get feedback from real world users more frequently.

Would love to collaborate more on Polar:

https://getpolarized.io/

... and see if we can share more infrastructure code but noticed you didn't have binaries. Just wanted to take it for a spin but binaries from July don't incorporate all your latest and greatest work.

**Comment by sentialx** [comment]
Yeah, that's a great idea. I will try to publish releases more frequently. Maybe not each week, because I don't have that much time (school etc.), but I think once per month.

**Comment by InputNeuron** [comment]
The trick is to make it easy or automated... which is often easier said than down.
