### ISSUE TITLE
Settings and Extensions won't open

### ISSUE THREAD

**Issue by theMackabu** [wexond/browser-base#136]
Maybe the same as #132

**Comment by AhmedMostafa16** [comment]
Settings and Extensions pages haven't implemented yet.

**Comment by theMackabu** [comment]
Ohhhh, can I change Change the weather format from C to F?
and why does chrome devtools open up?
and no linux icon? (elementary os)
[image: Picture]
Sajjaad Farzad
About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by sentialx** [comment]
At this moment you can change from C to F using source code and build Wexond by your own. This feature will be implemented the same as changing weather location.
