### ISSUE TITLE
No Bookmark Icons

### ISSUE THREAD

**Issue by theMackabu** [wexond/browser-base#137]
Cannot reproduce the icons (MacOS)

**Comment by sentialx** [comment]
I need more info about this, screens or something...

**Comment by theMackabu** [comment]
fine

**Comment by theMackabu** [comment]
![screen shot 2018-12-09 at 9 42 05 am](https://user-images.githubusercontent.com/32078755/49700668-b418f200-fb96-11e8-8bb7-eb59f8ff169a.png)

**Comment by theMackabu** [comment]
Can I help with wexond?
I have lots of html experience.
and some css experience.
I also mostly work in the chromebrew repository.
could I help I the builds?

**Comment by theMackabu** [comment]
also this is the expected result
![screenshot-1](https://user-images.githubusercontent.com/32078755/49700709-4de09f00-fb97-11e8-9c0a-419ea412f23f.png)
