### ISSUE TITLE
Add user data syncing with server.

### ISSUE THREAD

**Issue by sentialx** [wexond/browser-base#14]
Add user data syncing with server. This will allow users to sync history, bookmarks, extensions, settings with Nersent account.

**Comment by ghost** [comment]
Since i don't know if any nersent API exist, i'd rather use github's private gists, with github login api.

It's fairly easy to do with javascript and I think that an open source browser should rely on open source technologies rather than buying expensive databases and servers

**Comment by sentialx** [comment]
I'll create separate Github repository for the Nersent API that will be used in our VPS. The bookmarks data will be stored in a MySQL database.

**Comment by ghost** [comment]
Well, you'll see that it requires petabyte of disk space to store so much informations. Trust me, it's not feasible right now

And even using mysql is not a perfect solution. Probably something like mongodb would be better to manage arrays
