### ISSUE TITLE
How do you add a .crx chrome extension file?

### ISSUE THREAD

**Issue by theMackabu** [wexond/browser-base#141]
How?

**Comment by AhmedMostafa16** [comment]
We don't add .crx files. We use the source of the extension to install it.

**Comment by theMackabu** [comment]
How?

**Comment by AhmedMostafa16** [comment]
Get the source code of the extension. Then go to .wexond/userdata/extensions, then add the folder of source code on this directory.

**Comment by theMackabu** [comment]
what about on macOS Mojave?

-- SajjaadF

**Comment by AhmedMostafa16** [comment]
I didn't try MacOS before but I think these directories are same on Linux and Mac. I think it is ~/.wexond/extensions

**Comment by theMackabu** [comment]
No I tried going to it and it would not be a directory

Sent from Mail for Windows 10

**Comment by sentialx** [comment]
unzip extension source to %HOMEDIR%/.wexond/extensions
