### ISSUE TITLE
Can't Visit Bookmarked Sites.

### ISSUE THREAD

**Issue by erickserna** [wexond/browser-base#145]
I bookmark tons of sights on Wexond. Mainly GitHub. I wanted to export my bookmarks as an HTML file but instead I decided to copy their addresses and paste it into my other browser. The thing is that unlike the history where you can right click and open in new tab/window, I can't do that. I tried dragging the bookmark into a new tab but it doesn't work. Please fix this.

**Comment by sentialx** [comment]
Fixed in 6127edb1510280450d3b9f2791e9a75d365a1e53
