### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by sentialx** [wexond/browser-base#148]
Of course, Wexond has to have keyboard shortcuts like in other browsers and also make them customizable. Here is the list of suggested shortcuts:
- [x] New tab - `ctrl` + `t`
- [x] Close tab - `ctrl` + `w`
- [x] Focus address bar - `ctrl` + `l`
- [ ] Home - `ctrl` + `shift` + `h`

Any suggestions would be welcomed.

**Comment by zirnc** [comment]
You can also add these: 
- [x] New window - `ctrl` + `n`
- [x] Quit wexond - `ctrl` + `shift` + `q`
- [x] Find - `ctrl` + `f`
- [ ] Save page as - `ctrl` + `s`

**Comment by xnerhu** [comment]
These also would be very usefull: 
- [x] Switch to next tab - `ctrl` + `tab`
- [ ] Switch to nth tab - `ctrl` + `number`
- [x] Toggle Overlay - `alt` + `space`
- [ ] Open newtab in focused tab - `alt` + `home`
- [x] Open previous page in focused tab - `alt` + `arrow left`
- [x] Open next page in current tab - `alt` + `arrow right`
- [x] Close focused tab - `ctrl` + `w`

**Comment by davidraywilson** [comment]
ctrl + r currently refreshes the entire browser rather than the current tab.

**Comment by fanvyr** [comment]
@davidraywilson was already reported and fixed in [#180](https://github.com/wexond/wexond/issues/180)

**Comment by davidraywilson** [comment]
@fanvyr that issue was opened after my comment

**Comment by samollari** [comment]
- [x] Reopen closed tab: `ctrl + shift + t`

**Comment by sentialx** [comment]
Available keyboard shorcuts can be found here: https://github.com/wexond/wexond/blob/master/docs/keyboard-shortcuts.md
Closing.
