### ISSUE TITLE
I need to make a decision

### ISSUE THREAD

**Issue by IceHacks** [wexond/browser-base#150]
So I have made/was going make web browsers before and I was thinking of making a new one with Electron. But then I saw this and it looks really cool, it's got the design I like and a lot of the same features I would add. So my problem is do I want to help you make this or do I want to make my own browser. I don't know why I can't decide so I thought I would maybe ask you. I haven't started my browser yet.

Edit:
Also my Discord is IceIceBaby#2875 in case I don't respond here.

**Comment by sentialx** [comment]
Hi, feel free to open pull requests in here!

**Comment by sentialx** [comment]
Closing since it's not a Wexond issue, rather a question.

**Comment by IceHacks** [comment]
Ok, understood.
