### ISSUE TITLE
cloned master but npm start doesn't work

### ISSUE THREAD

**Issue by hanoii** [wexond/browser-base#151]
Just checked out master but I can't start it. Did an npm install with node 10 on latest osx. npm is 6.5.0.

it just the following error:

<img width="532" alt="screen shot 2019-02-05 at 16 35 39" src="https://user-images.githubusercontent.com/677879/52299420-18242080-2964-11e9-8528-1a6e3c8c46a3.png">

**Comment by sentialx** [comment]
Try running `npm run dev`.

**Comment by hanoii** [comment]
that did work, I did `npm start` as per the readme

thanks!
