### ISSUE TITLE
You might want to use my fork of contains-ads

### ISSUE THREAD

**Issue by IceHacks** [wexond/browser-base#152]
I forked `contains-ads` a no longer updated `brave/ad-block` tool for use with SkateBrowser I suggest using it as it would make implementing `ad-block` a lot easier. I am updating it and you could fork it. The advantages of mine is that I added the EasyList Privacy list to it and an option to disable any of the lists. Just thought it might be useful for you to know.

**Comment by sentialx** [comment]
Could you link your contains-ads fork?

**Comment by IceHacks** [comment]
Oh yes, sorry I forgot I didn't fork it on my main account. https://github.com/frozen-software/contains-ads is the repository.

**Comment by sentialx** [comment]
How is this different from `brave/ad-block`?

**Comment by IceHacks** [comment]
It's just a layer over `brave/ad-block` to make life easier with preconfigured lists and functions.

**Comment by sentialx** [comment]
I don't need additional abstraction layers and dependencies, closing.

**Comment by IceHacks** [comment]
I can understand that. I personally found it hard understanding `ad-block` without it but all people's brains are different.
