### ISSUE TITLE
Malware acording to bitdefender

### ISSUE THREAD

**Issue by ghost** [wexond/browser-base#155]
Bitdefender thinks that the following is malware:

- Browser
- Uninstaller
- Updater

https://imgur.com/a/W8YRZOD

**Comment by sentialx** [comment]
I can't do much about this issue. It's just a fake alarm, because it's not trusted by Bitdefender.

**Comment by Ylacat** [comment]
As a security measure, I checked with Mcfee labs to be sure it's safe to use. And even they are suspicious. At this point, I have submitted a sample for testing with the antivirus companies. I'll post here if they find anything within 30 days :)
