### ISSUE TITLE
Downgrade electron

### ISSUE THREAD

**Issue by ghost** [wexond/browser-base#16]
Downgrade to `electron@1.4.16` to fix transparency issues, as you know it's a well-known issue discussed here: https://github.com/electron/electron/issues/2170

On ubuntu 16.04 it's completely buggy with the latest version of electron, tough the 1.4 seems to fix

Related to #7

**Comment by ghost** [comment]
Since it's an upstream bug the only thing that we can do is just downgrade for now

**Comment by sentialx** [comment]
Yeah I know and I will downgrade until the bug will be fixed, but the only one thing that worries me is that Wexond willn't get the newest Chromium 👎 as of today.

**Comment by sentialx** [comment]
Does the 1.4.16 version work properly on Linux? I don't know because I don't have Linux on my PC, so I can't determine whether is it working or not.

**Comment by ghost** [comment]
Yes i've just tested it and 1.4.16 works like a charm, though the position is often wrongly-calculated. I belive this isn't related to electron but to the way that we calculate the x and y offset of the context menu

**Comment by sentialx** [comment]
Can you send me a screenshot of wrongly calculated position of menu? I need to determine what is the problem.

**Comment by ghost** [comment]
I'll just open a new issue in a second
