### ISSUE TITLE
OAuth in new window crashes app

### ISSUE THREAD

**Issue by timsu** [wexond/browser-base#162]
When I launch Asana (asana.com) and click Login > Use Google Account, it opens a new window successfully to do Google OAuth. However, when the window closes, the entire browser window also closes. There doesn't seem to be much in the logs:

```
14:42:57: Client connected
14:43:08: Connection closed
```

**Comment by sentialx** [comment]
Hmm, but if I login via the window, not the new tab, it doesn't crash. Weird.

**Comment by sentialx** [comment]
Fixed in 6cb43861264b19b2380df422dbf22a1cd02ca69d

**Comment by timsu** [comment]
thanks for the update!
