### ISSUE TITLE
Broken buttons, white screen & missing navbar

### ISSUE THREAD

**Issue by GamingGeek** [wexond/browser-base#163]
I recently found this and thought it was extremely good looking and I wanted to try modding it. I forked it and cloned it to my pc. When I ran `npm run dev`, it loaded fine but there were a few issues...
![image](https://user-images.githubusercontent.com/29981918/55759809-3dabd400-5a52-11e9-9ae3-99a0f1fc29db.png)
1. Clicking the X on `New group` caused the window to go completely white
2. None of these buttons work.
and sometimes, the navbar would just dissapear...
![image](https://user-images.githubusercontent.com/29981918/55759866-6af88200-5a52-11e9-9925-c157a886b8ea.png)

So I decided to try `npm run start` which just produced a completely white window. Using `npm run compile-win32` will make the .exe in the dist folder but has the same issues as using `npm run dev`. It also said about `GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"` so it would be nice if instructions on how to do this were on the README.md.

Speaking of the readme, you claim to have a **Built-in ad-block** which is either non-existent or broken
![image](https://user-images.githubusercontent.com/29981918/55760071-fc67f400-5a52-11e9-8aba-7cd7cf713169.png)

I hope you can get these issues resolved as I would love to use wexond as my main browser

**Comment by kierandrewett** [comment]
Hi I am experiencing the same issues as you.

**Comment by sentialx** [comment]
Hi, tomorrow should be an another update which will fix these issues. Wexond doesn't have any adblocker built-in, but it will be added soon. Don't mind about the error about publishing to GitHub, just check the dist folder.

**Comment by sentialx** [comment]
Also you can install uBlock Origin by placing its folder to ~/.wexond/extensions

**Comment by kierandrewett** [comment]
Thanks for the fast response, any chance you have a Discord I could message you on in case of any more issues? I don't want to open a fresh ticket.
Thanks, Ender

**Comment by sentialx** [comment]
It would be better if you had opened a new ticket when encountered a new issue, but sure my Discord is Sential#9122

**Comment by kierandrewett** [comment]
Mine is Ender#0002

**Comment by kierandrewett** [comment]
Hello, when running `npm run start`, shows white screen, `npm run dev` works, but nothing works like @GamingGeek said. And when I try compile it doesn't even create the exe, but returns this error https://hasteb.in/gupowute.sql It doesn't continue.

**Comment by sentialx** [comment]
Please `git pull` latest changes and then run `npm run dev`. `npm start` only starts Electron, but without the development server, that's why you use `npm run dev`.

**Comment by kierandrewett** [comment]
Hi I occasionally get the invisible navbar thing, but it seems to work. None of the buttons work on the overlay, weather, extensions, etc. I've git pulled and it's all up to date. So I'm not sure why it doesn't work.

**Comment by sentialx** [comment]
It's not implemented yet

**Comment by kierandrewett** [comment]
I also found it takes forever to load a page and to navigate pages are buggy.
https://i.imgur.com/vdjPrvY.gifv

**Comment by kierandrewett** [comment]
Hi I just tried to build it again, and this time got this error https://hasteb.in/dijomali.css
