### ISSUE TITLE
Top Sites Favicon's won't appear in 2.0.0-beta.6

### ISSUE THREAD

**Issue by theMackabu** [wexond/browser-base#165]
The Icons for the top sites are
_nonexistent_
![Screen Shot 2019-04-11 at 11 28 46 AM](https://user-images.githubusercontent.com/32078755/55982150-21c05200-5c4d-11e9-9e5f-46cf0acd2da3.png)

**Comment by sentialx** [comment]
Perhaps they were not saved, try visiting github.com once again

**Comment by theMackabu** [comment]
I did

**Comment by theMackabu** [comment]
Actually no Favicon IN _general_ 
![Screen Shot 2019-04-11 at 11 35 30 AM](https://user-images.githubusercontent.com/32078755/55982524-f427d880-5c4d-11e9-984a-89eeb36cc253.png)

**Comment by sentialx** [comment]
Try removing `.wexond/storage/favicons.db`, perhaps the favicon database was corrupted in some way.

**Comment by theMackabu** [comment]
Ill try

**Comment by theMackabu** [comment]
Nope still broken

**Comment by theMackabu** [comment]
![Screen Shot 2019-04-11 at 11 39 08 AM](https://user-images.githubusercontent.com/32078755/55982753-6f898a00-5c4e-11e9-8b91-498af89ec5fc.png)

**Comment by theMackabu** [comment]
Nope fixed

**Comment by theMackabu** [comment]
Thanks!
