### ISSUE TITLE
Lock Bug (Initial Screen) | Impossible to use on modest computers

### ISSUE THREAD

**Issue by juniorbotelho** [wexond/browser-base#168]
After this last update the browser was impossible to be use thanks to the exaggeration that went to effects, both blur and transition effects, of course the concept is great, but I believe that many of its users may have a weak PC like mine and will end up encountering the same problems (Crashes, Slowdown, Impossible to Use). I believe that minimalism is in the opposite direction to what you have implemented in this last update. (I apologize for English, I turned to the translator to express both my gratitude for your Browser and my constructive criticism).

**Comment by sentialx** [comment]
Hi, I've removed the blur and the screenshot behind in commit f1dd5b96f49924d2d6a0bcf1b941b94ef5786f44. Could you build the latest version and test it?
