### ISSUE TITLE
Spotify Web Player / Location Services

### ISSUE THREAD

**Issue by davidraywilson** [wexond/browser-base#174]
Spotify's web player appears to be broken. I would also like the ability to share location on websites like Hulu. Thanks! Really enjoying the browser!

**Comment by sentialx** [comment]
On which version of Wexond this problem occurs?

**Comment by davidraywilson** [comment]
I'm running the latest: 2.0.0-beta.9 on Windows 10

**Comment by sentialx** [comment]
It seeems the Spotify player is working normally for me

**Comment by davidraywilson** [comment]
The pages appear to load correctly but it never allows me to play anything. Clicking the play button doesn't do anything.

**Comment by sentialx** [comment]
Hmm you're right, I will see if that behavior appears without the built-in adblocker

**Comment by sentialx** [comment]
That's not adblocker issue. Perhaps Spotify uses some APIs which Electron doesn't support by default. Do you know these?

**Comment by davidraywilson** [comment]
It looks like it's failing to load a chrome extension along with a couple other console errors I'm seeing. I'm not familiar with how Electron works for this.

Here's one of the errors that show a couple times:

GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_NOT_IMPLEMENTED

**Comment by sentialx** [comment]
As I can see it's a problem related with Widevine, but it's not open source and I don't have any access to it. I've wrote an email to Google but they didn't respond. #175

**Comment by sentialx** [comment]
Merging this to #209
