### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by ldong2014** [wexond/browser-base#181]
npm WARN lifecycle wexond@2.0.0-beta.9~postinstall: cannot run in wd %s %s (wd=%s) wexond@2.0.0-beta.9 electron-builder install-app-deps /home/ldong/wexond
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.8
npm WARN wexond@2.0.0-beta.9 No license field.

**Comment by sentialx** [comment]
These are only warnings I guess
