### ISSUE TITLE
Not able to navigate to any page 

### ISSUE THREAD

**Issue by aamorozov** [wexond/browser-base#182]
Once I've pressed the enter within the url bar, the browser opens a new tab but it is blank.

#### Meta
Version: 2.0.0-beta.10.
OS: MacOS Mojave 
NPM: 6.9.0
Node: v11.14.0

#### Entering page url 
![Screen Shot 2019-04-19 at 9 19 57 AM](https://user-images.githubusercontent.com/10227658/56425957-5901b500-6284-11e9-9d11-39df8293398a.png)

#### Pressing enter 
![Screen Shot 2019-04-19 at 9 20 01 AM](https://user-images.githubusercontent.com/10227658/56425963-5ef79600-6284-11e9-8ede-380e7a876a2b.png)

**Comment by sentialx** [comment]
Thanks for your issue, I haven't noticed that. Will fix as fast as I can, but at the moment you can use previous version.

**Comment by aamorozov** [comment]
Thank you! Looks like it does work in 2.0.0-beta.9

**Comment by sentialx** [comment]
I've released 2.0.0-beta.11 version which fixes the problem.
