### ISSUE TITLE
Could not locate the bindings file - Windows

### ISSUE THREAD

**Issue by Crackiii** [wexond/browser-base#196]
I am trying to  `npm run dev`, run the app in developer mode. But I am getting an error at run time, which says : Could not locate the bindings file. Tried:

 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\build\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\build\Debug\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\build\Release\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\out\Debug\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\Debug\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\out\Release\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\Release\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\build\default\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\compiled\12.0.0\win32\x64\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\addon-build\release\install-root\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\addon-build\debug\install-root\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\addon-build\default\install-root\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\lib\binding\node-v70-win32-x64\addon.node
    at bindings (C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\dist\classes\window.js:8:32)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\dist\index.js:3:18)

**Comment by sentialx** [comment]
Do you have Python 2.7 and BuildTools installed?

**Comment by Crackiii** [comment]
yes, I do. Those were installed without any issue, I followed the docs for the proposed commands

**Comment by sentialx** [comment]
Try `npm run postinstall`. I think the native dependencies didn't rebuild properly.

**Comment by Crackiii** [comment]
Still same issue after running the command `npm run postinstall`

**Comment by sentialx** [comment]
Try removing node_modules and running npm install. I can see the native modules didn't build.

**Comment by Crackiii** [comment]
Ok. let me give it a try

**Comment by Crackiii** [comment]
There's still the same error.

**Comment by sentialx** [comment]
Do you have Node.js 12?

**Comment by Crackiii** [comment]
The node version is 8.11.3

**Comment by sentialx** [comment]
This version is way too much outdated.

**Comment by Crackiii** [comment]
Let me try the new version

**Comment by Crackiii** [comment]
Version updated to 12, not still same errors.

**This is the log**
C:\wamp64\www\Fiverr\Browser\wexond-master>npm i -g windows-build-tools

> windows-build-tools@5.1.0 postinstall C:\Users\Nadeem Ahmad\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js



Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\Nadeem Ahmad\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Python 2.7.15 is already installed, not installing again.

Now configuring the Visual Studio Build Tools..

All done!

+ windows-build-tools@5.1.0
updated 1 package in 62.317s




**C:\wamp64\www\Fiverr\Browser\wexond-master> npm run dev**

> wexond@2.1.0 dev C:\wamp64\www\Fiverr\Browser\wexond-master
> cross-env NODE_ENV='dev' node fuse.js

--- FuseBox 3.7.1 ---

--------------------------
Bundle "view-preload"

└──  (18 files,  33.5 kB) default
size: 33.5 kB in 311ms

--------------------------
Bundle "background-preload"

└──  (18 files,  26.6 kB) default
size: 26.6 kB in 430ms

--------------------------
Bundle "main"

└──  (48 files,  82.8 kB) default
size: 82.8 kB in 511ms

  --------------

  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\windows\close.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\windows\maximize.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\windows\minimize.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\add.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\back.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\forward.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\refresh.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\close.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\search.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\page.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\download.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\history.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\bookmarks.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\settings.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\extensions.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\window.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\more.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\find.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\edit.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\down.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\arrow-back.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\star.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\star-filled.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\fire.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\delete.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\up.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\shield.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\night.svg weren't loaded. Missing a plugin?
  → WARNING The contents of C:\wamp64\www\Fiverr\Browser\wexond-master\src\shared\resources\icons\weather\few-clouds.png weren't loaded. Missing a plugin?

  --------------


--------------------------
Bundle "app"

└──  (153 files,  253.9 kB) default
└── events@0.0.0 8 kB (0 files)
└── fusebox-hot-reload@0.0.0 7.6 kB (0 files)
└── fusebox-websocket@0.0.0 2.9 kB (0 files)
size: 272.3 kB in 2s 184ms
  →
-----------------------------------------------------------------
Development server running http://localhost:4444 @ 3.7.1
-----------------------------------------------------------------

23:11:40: HMR is enabled

> wexond@2.1.0 start C:\wamp64\www\Fiverr\Browser\wexond-master
> cross-env ENV='dev' electron .


 App threw an error during load
Error: Could not locate the bindings file. Tried:
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\build\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\build\Debug\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\build\Release\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\out\Debug\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\Debug\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\out\Release\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\Release\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\build\default\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\compiled\12.0.0\win32\x64\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\addon-build\release\install-root\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\addon-build\debug\install-root\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\addon-build\default\install-root\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\lib\binding\node-v70-win32-x64\addon.node
    at bindings (C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\dist\classes\window.js:8:32)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\node-window-manager\dist\index.js:3:18)

**Comment by Crackiii** [comment]
Can you test it on windows, the commands, and check how its working there ? or if its running there or not ?

**Comment by sentialx** [comment]
Basically I'm working on Windows everyday

**Comment by Crackiii** [comment]
Do you use the same process, Am I missing something ? 
Node is installed, 
Electron is Installed,
Windows build tools installed,

What else could be there ?

**Comment by Crackiii** [comment]
The error is updated, somehow solved the issue.

 App threw an error during load
Error: Cannot find module 'electron-extensions'
Require stack:
- C:\wamp64\www\Fiverr\Browser\wexond-master\build\main.js
- C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
    at Function.Module._resolveFilename (C:\wamp64\www\Fiverr\Browser\wexond-master\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:577:27)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at f (C:\wamp64\www\Fiverr\Browser\wexond-master\build\main.js:1240:1092)
    at u (C:\wamp64\www\Fiverr\Browser\wexond-master\build\main.js:1240:1430)
    at c (C:\wamp64\www\Fiverr\Browser\wexond-master\build\main.js:1240:2750)
    at b.require (C:\wamp64\www\Fiverr\Browser\wexond-master\build\main.js:1240:3346)
    at Object.<anonymous> (C:\wamp64\www\Fiverr\Browser\wexond-master\build\main.js:20:31)

**Comment by sentialx** [comment]
Yeah, the package is not available yet on npm (WIP). https://github.com/wexond/electron-extensions

**Comment by Crackiii** [comment]
Have to install it manually ??

**Comment by sentialx** [comment]
Try npm install wexond/electron-extensions

**Comment by Crackiii** [comment]
Installed, but have the same problem.

`wexond/electron-extensions` this command worked. But display the same error

**Comment by sentialx** [comment]
Try now `npm install electron-extensions`

**Comment by Crackiii** [comment]
First time both commands worked, but the error remained. I then unzipped the files again and started over, and not the these last two commands doesn't works. Says : 


C:\wamp64\www\Fiverr\Browser\wexond-master>npm install wexond/electron-extensions
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm ERR! code ETARGET
npm ERR! prepareGitDep npm ERR! notarget No matching version found for fast-future@src1.0.2
npm ERR! prepareGitDep npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! prepareGitDep npm ERR! notarget a package version that doesn't exist.
npm ERR! prepareGitDep npm ERR! notarget
npm ERR! prepareGitDep npm ERR! notarget It was specified as a dependency of 'leveldown'
npm ERR! prepareGitDep npm ERR! notarget
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\Nadeem Ahmad\AppData\Roaming\npm-cache\_logs\2019-05-20T20_08_39_354Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nadeem Ahmad\AppData\Roaming\npm-cache\_logs\2019-05-20T20_08_39_446Z-debug.log


0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'wexond/electron-extensions'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.2.0
4 verbose npm-session a0009acc921e20f8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose prepareGitDep undefined: installing devDeps and running prepare script.
8 error prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
8 error prepareGitDep npm ERR! code ETARGET
8 error prepareGitDep npm ERR! notarget No matching version found for fast-future@src1.0.2
8 error prepareGitDep npm ERR! notarget In most cases you or one of your dependencies are requesting
8 error prepareGitDep npm ERR! notarget a package version that doesn't exist.
8 error prepareGitDep npm ERR! notarget
8 error prepareGitDep npm ERR! notarget It was specified as a dependency of 'leveldown'
8 error prepareGitDep npm ERR! notarget
8 error prepareGitDep
8 error prepareGitDep npm ERR! A complete log of this run can be found in:
8 error prepareGitDep npm ERR!     C:\Users\Nadeem Ahmad\AppData\Roaming\npm-cache\_logs\2019-05-20T20_08_39_354Z-debug.log
9 silly fetchPackageMetaData error for github:wexond/electron-extensions premature close
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 13739ms
12 verbose stack Error: premature close
12 verbose stack     at PassThrough.onclose (C:\Program Files\nodejs\node_modules\npm\node_modules\end-of-stream\index.js:47:67)
12 verbose stack     at PassThrough.emit (events.js:201:15)
12 verbose stack     at emitCloseNT (internal/streams/destroy.js:68:8)
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
13 verbose cwd C:\wamp64\www\Fiverr\Browser\wexond-master
14 verbose Windows_NT 10.0.17134
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "wexond/electron-extensions"
16 verbose node v12.2.0
17 verbose npm  v6.9.0
18 error premature close
19 verbose exit [ 1, true ]

**Comment by sentialx** [comment]
Please try `npm install electron-extensions` instead of `npm install wexond/electron-extensions`

**Comment by Crackiii** [comment]
Installed, and the old error is displayed again. :(

**Comment by Iceberg1109** [comment]
I have the same problem.

I have installed Python and build tools successfully.
Python is 2.7 and Node is 12.2.0

This is the error.
 App threw an error during load
Error: Could not locate the bindings file. Tried:
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\build\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\build\Debug\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\build\Release\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\out\Debug\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\Debug\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\out\Release\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\Release\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\build\default\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\compiled\12.0.0\win32\x64\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\addon-build\release\install-root\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\addon-build\debug\install-root\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\addon-build\default\install-root\addon.node
 ΓåÆ F:\wexond\wexond-master\node_modules\node-window-manager\lib\binding\node-v70-win32-x64\addon.node
    at bindings (F:\wexond\wexond-master\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (F:\wexond\wexond-master\node_modules\node-window-manager\dist\classes\window.js:8:32)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (F:\wexond\wexond-master\node_modules\node-window-manager\dist\index.js:3:18)

I have tried deleting node modules and reinstall them.

What else can I try now?

**Comment by sentialx** [comment]
Try `npm config set msvs_version 2015 --global` and reinstall node modules

**Comment by Iceberg1109** [comment]
Thanks for your help

so the runt these commands?
npm config set msvs_version 2015 --global
npm i -g windows-build-tools
npm install
npm run dev

Am I right?

**Comment by Iceberg1109** [comment]
I have tried it but it still install visual studio build tools 2017, not 2015

How can I fix this?

Please help me.

**Comment by Iceberg1109** [comment]
Something below, when I run npm install
Is it okay?

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

And other thing
npm WARN wexond@2.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

Can you make any guess?

**Comment by Crackiii** [comment]
I have made a video where I have show, How am I installing it, please tell me if I am missing something : 
https://youtu.be/wtDixIiFvD0

**Comment by Iceberg1109** [comment]
I have checked your video.

At the end of video, I can see the same error "Could not locate bindings file".
After this part, did you edit the some json files?

**Comment by sentialx** [comment]
Ah I see

**Comment by Iceberg1109** [comment]
Please help me

**Comment by sentialx** [comment]
Try git pull and reinstalling deps

**Comment by Iceberg1109** [comment]
I will try it now

**Comment by Crackiii** [comment]
Ok, let me give it a try !

**Comment by Crackiii** [comment]
@Smart1109  I didn't edit anyfile.

**Comment by Crackiii** [comment]
same errors after following the same steps as in the video.

but new pull request .

 App threw an error during load
Error: Could not locate the bindings file. Tried:
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\build\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\build\Debug\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\build\Release\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\out\Debug\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\Debug\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\out\Release\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\Release\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\build\default\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\compiled\12.0.0\win32\x64\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\addon-build\release\install-root\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\addon-build\debug\install-root\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\addon-build\default\install-root\addon.node
 ΓåÆ C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\lib\binding\node-v70-win32-x64\addon.node
    at bindings (C:\wamp64\www\Fiverr\Browser\wexond\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\dist\classes\window.js:8:32)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\wamp64\www\Fiverr\Browser\wexond\node_modules\node-window-manager\dist\index.js:3:18)

**Comment by sentialx** [comment]
You need to download the new source

**Comment by Crackiii** [comment]
I did download the new source by making a pull request to it

**Comment by sentialx** [comment]
Can you send me screenshot of your npm install logs?

**Comment by Iceberg1109** [comment]
Hi
here is the screenshot
![Screenshot_5](https://user-images.githubusercontent.com/49850848/58083069-de151c80-7bea-11e9-846a-572750a56d5b.png)
![Screenshot_6](https://user-images.githubusercontent.com/49850848/58083071-deadb300-7bea-11e9-9539-195121d5e526.png)

**Comment by Crackiii** [comment]
Yeah sure
![Screenshot (400)](https://user-images.githubusercontent.com/39433365/58083207-fe84ad00-7bd1-11e9-9244-fcf901ee568e.png)

**Comment by Crackiii** [comment]
Does this seem to be the error ? 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by Iceberg1109** [comment]
I don't have any idea.

But there is no error when npm install, only those warnings.
Maybe they are problems,

But how to fix it?

**Comment by Crackiii** [comment]
That's what I am confused about @Smart1109 .

@sentialx  can you install it on your window, and share a video or maybe screenshots, so that we can see if it works for you ?

**Comment by sentialx** [comment]
@Smart1109 Well, the warnings have nothing to do with Wexond. Please join our Discord and I will help you there https://discord.gg/yAA8DdK

**Comment by Iceberg1109** [comment]
Excuse me, could you tell me how join Discord?

**Comment by sentialx** [comment]
@Smart1109 https://discord.gg/yAA8DdK

**Comment by Crackiii** [comment]
Invalid Invite @Smart1109

**Comment by sentialx** [comment]
Ah maybe it expired: https://discord.gg/6dU6hC

**Comment by Crackiii** [comment]
Got in
