### ISSUE TITLE
Control the Notifications API

### ISSUE THREAD

**Issue by ofekashery** [wexond/browser-base#199]
Currently websites can send [push notifications](https://developer.mozilla.org/en-US/docs/Web/API/notification) even without a permission.

```js
Notification.permission // => "granted"
```

**Comment by xnerhu** [comment]
Thank you for your issue. We will need to create a permission dialog to also allow websites use microphone, camera etc.

**Comment by sentialx** [comment]
I think Wexond declines all permission requests by default.

**Comment by sentialx** [comment]
Merging this to #209.
