### ISSUE TITLE
Add context menu

### ISSUE THREAD

**Issue by sentialx** [wexond/browser-base#2]
Add context menu. I need your suggestions how the menu can look like.

**Comment by ghost** [comment]
I expect this from a modern browser's context menu:

- Back/forward/reload(with md-icons)
- Save page / print it
- View source / inspect

Nothing else. Period. The rest will be stored in the toolbar at the top(settings, addons management, etc...)

**Comment by sentialx** [comment]
Thank you very much for your suggestions, I will probably separate some context menu items like history, settings etc. to another menu like navigation drawer or something like that. As you can see in the screenshot of Wexond, there is context menu with tabs: Actions (open link in new tab, print etc.), Menu (settings, history etc.) and Apps (extensions).

**Comment by ghost** [comment]
I'll try it out today morning
