### ISSUE TITLE
blank window since 2.0.2

### ISSUE THREAD

**Issue by rapha8l** [wexond/browser-base#203]
Hi,
Since 2.0.2, I get a totally blank window instead of the browser window on Linux
Even when launching from terminal, I do not get any errors

Thanks

**Comment by sentialx** [comment]
Please see #195. It happens after update.

**Comment by rapha8l** [comment]
It works !
I deleted my ~/.config/wexond, but did not notice there  was a ~/.wexond
Don't know how it is for Mac Os, but ~/.config is more convenient for dotfiles
Thanks for your help
