### ISSUE TITLE
Add tabs preview

### ISSUE THREAD

**Issue by sentialx** [wexond/browser-base#208]
It would be great to see tab's webContents screenshot on hover.

**Comment by moeenio** [comment]
Something like this ?
![wexond preview](https://user-images.githubusercontent.com/37651007/61274985-36ad0400-a7ad-11e9-8f50-9f4d13b97755.png)

**Comment by sentialx** [comment]
@locness3 Unfortunately, it has to be done in a separate window since the BrowserView covers the app and doesn't live in app's DOM.
