### ISSUE TITLE
Cannot GET /permissions.html

### ISSUE THREAD

**Issue by infi** [wexond/browser-base#217]
Hey,  
  
When I run unmodified Wexond in dev mode (using `npm run dev`) on x64 Lubuntu 19.04, I get an overlay over the web browser's UI, which states that permissions.html is not a valid URL to perform a GET request on, like that: 
![image](https://user-images.githubusercontent.com/45950794/60388689-80ab9f80-9ab5-11e9-8cca-32ffba4206f7.png)  
  
This happens definitely after pressing the shield button in the tab bar, but I think I've seen it pop up randomly too.  
  
Developer Tools:
![image](https://user-images.githubusercontent.com/45950794/60388890-63c49b80-9ab8-11e9-8e5d-fded24df6a41.png)

**Comment by sentialx** [comment]
I noticed it also only on dev mode. It's a fuse-box bundler bug. Try running `npm run build`, this should generate the missing files and then try `npm run dev`.

**Comment by sentialx** [comment]
@spVierSechs Did it work for you?

**Comment by infi** [comment]
Yes, it did. Thank you!

**Comment by theMackabu** [comment]
Thanks
