### ISSUE TITLE
Error with npm install

### ISSUE THREAD

**Issue by kevinmuscara** [wexond/browser-base#221]
![image](https://user-images.githubusercontent.com/29820047/60474374-9056ef80-9c3f-11e9-84bc-973e81527eef.png)
help

**Comment by sentialx** [comment]
You have to run `npm i -g windows-build-tools` as administrator and make sure you have Node.js 12 installed.

**Comment by kevinmuscara** [comment]
ooohhh, you should probably clarify somewhere that u have to have 12 or above

**Comment by kevinmuscara** [comment]
i updated to node.js 12 and i still can't run the same command without it giving the same errors

**Comment by ofekashery** [comment]
Same

**Comment by sentialx** [comment]
@ofekashery @Kevqn Does this problem still occur on `master`? I tested Wexond on a freshly installed Windows 10 1903 VM and ran these commands:
(as administrator)
```
npm i -g windows-build-tools
```
(in the Wexond directory)
```
npm i
npm run dev
```

**Comment by ofekashery** [comment]
I'm on Mac and it works now
