### ISSUE TITLE
Can't install chrome extension

### ISSUE THREAD

**Issue by hampoelz** [wexond/browser-base#222]
Hey,
How can I install a chrome extension? I downloaded the` .crx` file and decompilled it via [crxextractor.com](https://crxextractor.com/), and created a folder with the source code of the extension in `C:\Users\<user>\.wexond\extensions`, when I now open Wexond the extension button is disabled and there is no Extension symbol when I'm on a website like on the screenshot in `Readme.md` file ...

**Comment by sentialx** [comment]
Currently the support for Chrome extensions is limited and not all extensions work. See #110

**Comment by sentialx** [comment]
@hampoelz Now, you can install extensions directly from Chrome webstore.

**Comment by hampoelz** [comment]
Nice, thank you
