### ISSUE TITLE
Weird tab behavior

### ISSUE THREAD

**Issue by cylexVEVO** [wexond/browser-base#224]
If you right click on a tab and then select "reload" the tab will think you are holding down mouse one to drag it, even though you aren't holding anything.

Video of it happening:
[simplescreenrecorder-2019-07-02_15.02.17.zip](https://github.com/wexond/wexond/files/3351920/simplescreenrecorder-2019-07-02_15.02.17.zip)

**Comment by moeenio** [comment]
Can't reproduce on macOS.

**Comment by moeenio** [comment]
nevermind. I can reproduce.
