### ISSUE TITLE
Tab Bar on overlay breaks on Mac

### ISSUE THREAD

**Issue by theMackabu** [wexond/browser-base#227]
Before:
![Screen Shot 2019-07-03 at 10 00 44 AM](https://user-images.githubusercontent.com/32078755/60611007-1d9e5f00-9d7a-11e9-8e4d-d9cfd3e5a6a7.png)
![Screen Shot 2019-07-03 at 10 00 37 AM](https://user-images.githubusercontent.com/32078755/60611008-1d9e5f00-9d7a-11e9-8577-d98e664d1de6.png)

After:
![Screen Shot 2019-07-03 at 10 00 18 AM](https://user-images.githubusercontent.com/32078755/60611032-2ee76b80-9d7a-11e9-8f70-d8c526c003ba.png)
![Screen Shot 2019-07-03 at 10 00 13 AM](https://user-images.githubusercontent.com/32078755/60611033-2ee76b80-9d7a-11e9-99ad-c3817db536e8.png)

Maybe Add it in settings page to enable / disable?

**Comment by sentialx** [comment]
How does it break? It's an expected behavior.

**Comment by theMackabu** [comment]
At least an option to disable it because it looks ugly...
