### ISSUE TITLE
electron_extensions_1.ExtensibleSession is not a constructor

### ISSUE THREAD

**Issue by fushilu06** [wexond/browser-base#229]
![image](https://user-images.githubusercontent.com/52439659/60868145-f9052400-a25e-11e9-8e4f-f3428582c174.png)

![image](https://user-images.githubusercontent.com/52439659/60868109-de32af80-a25e-11e9-9499-3746ed07b6c7.png)

**Comment by fushilu06** [comment]
![image](https://user-images.githubusercontent.com/52439659/60870452-7a5eb580-a263-11e9-817d-639584792808.png)

**Comment by sentialx** [comment]
Sorry, this is not the newest version. I will need to publish.
