### ISSUE TITLE
Using seperate menus in macOS menu bar

### ISSUE THREAD

**Issue by moeenio** [wexond/browser-base#237]
Would be great if things in macOS menu bar were separated in different, logical menus instead of being all in the Wexond menu. Would also love to have "about wexond", "hide wexond", etc in addition to "quit Wexond" in the Wexond menu, with the other options in the adequate menus.

**Comment by moeenio** [comment]
New tabg, New window etc. shouldn't be in the Wexond menu. And Wexond menu should have the default app menu items (about, services, preferences, hide...)

**Comment by moeenio** [comment]
View my previous comment @sentialx

**Comment by moeenio** [comment]
@sentialx, New tabg, New window etc. shouldn't be in the Wexond menu. And Wexond menu should have the default app menu items (about, services, preferences, hide...). Can you change this please?

**Comment by peanutbother** [comment]
I recommend to check out electron-create-menu on npm, which might be a handy helper for cross-platform menu templating
