### ISSUE TITLE
Legacy Google sign-in appears on Wexond, not the new one.

### ISSUE THREAD

**Issue by ghost** [wexond/browser-base#265]
When going to the Google sign in page (accounts.google.com/servicelogin), the **legacy page** comes up instead of the **redesigned page**. This may be small but this may pose **a greater issue as for support for websites**.

_New design displayed in Google Chrome 76.0.3809.87 (64-bit)_
![new](https://user-images.githubusercontent.com/53713662/62433660-b4df4380-b778-11e9-8cc4-2564b601747b.PNG)

_Legacy design displayed in Wexond 2.2.4 (64-bit)_
![legacy](https://user-images.githubusercontent.com/53713662/62433659-b4df4380-b778-11e9-9339-84a31d2a32fa.PNG)

**Comment by sentialx** [comment]
Google is known from destroying concurrent browsers hence the old design of some Google websites.

**Comment by ghost** [comment]
> Google is known from destroying concurrent browsers hence the old design of some Google websites.

Understandable. This seems like something Google would do. Thank you for your response.

**Comment by kierandrewett** [comment]
What you could try @sentialx is setting the user-agent to Chromium's one. https://electronjs.org/docs/api/web-contents#contentssetuseragentuseragent

**Comment by xylobol** [comment]
In the browser project (Lux) I work on, we've implemented a way for it to "fix" web compatibility issues by cross-comparing to a map (domain to fixes needed) and working from there.

**Comment by ctreadw6** [comment]
Setting the user agent to the latest Chrome user agent does indeed render the newer Google login design. However I think the user agent that is getting sent is appropriate. 

This is what Wexond is sending as the user agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Wexond/3.1.0 Chrome/76.0.3809.136 Electron/6.0.5 Safari/537.36

**Comment by xylobol** [comment]
Based on my testing, unless it exactly matches what Google expects (to a certain degree), Google just sends the old pages.
