### ISSUE TITLE
Warning if Closing Browser

### ISSUE THREAD

**Issue by ghost** [wexond/browser-base#266]
**Upon closing the browser, a warning message should come up asking for confirmation (Like Firefox or Opera).** 

_Opera closing message_
![opera](https://user-images.githubusercontent.com/53713662/62434064-7480c500-b77a-11e9-8517-1ed6831a3151.PNG)

This should have **toggles in the settings menu** for:
1. **No warning message.**
2. **Only displaying a warning message when closing with multiple tabs.**
3. **Always displaying a warning message** (Even with one tab).

 Hopefully this feature can be added.

**Comment by xnerhu** [comment]
Hello. We plan to implement it.
