### ISSUE TITLE
Themed Scrollbar for Every Site

### ISSUE THREAD

**Issue by ghost** [wexond/browser-base#268]
If there is a way to reskin the scrollbar for every website to fit the general aesthetic of Wexond, that would be phenomenal.

**Comment by xnerhu** [comment]
Hello. That's a nice idea. We'll think about implementing this.

**Comment by sentialx** [comment]
I don't understand why closing this?

**Comment by danimesq** [comment]
This should be an default, which will be impressive and different. But also popup an wizard for personalizing, making this easily and intuitively opt-out.

Also: https://github.com/wexond/desktop/issues/549
