### ISSUE TITLE
"[Website] is asking for location" notification appears every time I visit a website

### ISSUE THREAD

**Issue by ghost** [wexond/browser-base#270]
Every time I visit for example, Google, the "[Website] wants to: Know your location" message appears. I don't think the selection you make is persistent (if I click on "Allow", the option will not persist when I visit the website again).

_The notification that appears_
![notification](https://user-images.githubusercontent.com/53713662/62434757-012c8280-b77d-11e9-86e0-12e972873e52.PNG)

Can this be fixed?

**Comment by sentialx** [comment]
Merging into #213
