### ISSUE TITLE
Hiding a window only hides the first child window

### ISSUE THREAD

**Issue by samollari** [wexond/browser-base#276]
**Bug description**

Hiding a Wexond window with others in it only hides the parent and first child.

**To Reproduce**

Dock a Wecond window inside another a few times then hide the topmost parent. It and its first child will hide but nothing else.

**Expected behavior**

Hiding the topmost window will hide all child windows.

**Screenshots**

[https://youtu.be/PSRPISXEapY]()

**Details:**
 - Operating System: Windows 10 1903
 - Wexond version: 2.2.3 (Latest commit ae0d45c)
 - Last known working Wexond version: n/a

**Additional context**

This may be better suited to be opened in [sentialx/multrin](url) but I haven't tested it there

**Comment by sentialx** [comment]
We plan to disallow stacking Wexond and Multrin windows.

**Comment by sentialx** [comment]
Multrin has been removed due to instability issues.
