### ISSUE TITLE
history

### ISSUE THREAD

**Issue by andrewg78** [wexond/browser-base#279]
**Bug description**

I expected portable USB version to save opened tabs and history to the pendrive from where the browser was ran.
Instead, all user's activity is saved to the localhost.

**Details:**
Windows
Wexond-2.2.4-win.zip

**Comment by sentialx** [comment]
I don't understand. Wexond saves user data to `~/.wexond`. Wexond isn't meant to be portable, it's meant to be fully featured web browser.
