### ISSUE TITLE
Maximise Button is not Functioning Correctly

### ISSUE THREAD

**Issue by ghost** [wexond/browser-base#281]
Hello. 
I have found out the maximise feature is not working correctly. After clicking the button, the window will fill the screen, but the window will still remain resizable and poses a problem especially when using the scrollbar with the mouse (as you may accidentally resize the window).

Thank you.

**Comment by sentialx** [comment]
@laemongrass Could you use the issue template? What OS? What version? etc

**Comment by ghost** [comment]
No problem, I will create a new issue with the correct information.
