### ISSUE TITLE
Maximize Button is not Functioning Correctly

### ISSUE THREAD

**Issue by ghost** [wexond/browser-base#282]
**Bug description**
On occasion, the maximize button is working by filling the entire screen with the window, but the window remains resizable (i.e. Not fully maximized)

**To Reproduce**
Press the maximize button and the window will still remain resizable.

**Expected behavior**
The window is meant to be non-resizable.

**Screenshots**
N/A

**Details:**
Windows 10 Insider Edition (64 Bit); Version 1903
Wexond 3.0.0
Wexond 2.2.4 was the last version of Wexond where this feature was working.

**Additional context**
N/A

**Comment by sentialx** [comment]
I can't reproduce it on Windows 10 1903 stable. Maybe it's somehow related with the insider build.

**Comment by ghost** [comment]
I think so. I will try reinstalling Wexond as just a confirmation of function. Will report the results back.

**Comment by ghost** [comment]
@sentialx A reinstalltation has worked so I assume it may have been a corrupt installtion. Thank you.
