### ISSUE TITLE
OAuth login on Discourse doesn't close login window when finished

### ISSUE THREAD

**Issue by moeenio** [wexond/browser-base#283]
**Bug description**
Logging in with GitHub on forum.yunohost.org (a discourse powered forum) opens a pop-up window, then when auth is complete, I expect the pop-up window to be closed and the site reloaded in main window. I have to manually close the popup, then reload the site.

**To Reproduce**
1. Go to forum.yunohost.org (I believe it happens with other discourse forums)
2. Click Login, then "via GitHub"
3. Login using GitHub
4. Notice the popup isn't closed at the end of the process.

**Details:**
 - Operating System: macOS 10.11.6
 - Wexond version: 3.0.1 I guess
 - Last known working Wexond version: N/A

**Comment by sentialx** [comment]
I think it might be related https://github.com/electron/electron/issues/19194

**Comment by moeenio** [comment]
The popups are basic BrowserWindows, without a BrowserWiew, no ?

**Comment by sentialx** [comment]
Can't reproduce it now.
