### ISSUE TITLE
Pin tabs feature.

### ISSUE THREAD

**Issue by freddity** [wexond/browser-base#285]
Something like in Google Chrome:

![image](https://user-images.githubusercontent.com/41485166/62859250-e3bb6380-bcfc-11e9-9f4f-c973cbdc415c.png)

A tab could be pinned; pinned tab would be unremovable. To remove, tab have to be unpin. This feature could be really helpful so that cards aren't mistaken. For example you could pin trello, evernote, gmail or other app which are necessary sites for work.

**Comment by sentialx** [comment]
Fixed in #290
