### ISSUE TITLE
Wexond is inefficient and unwieldy

### ISSUE THREAD

**Issue by ghost** [wexond/browser-base#286]
![image](https://user-images.githubusercontent.com/29343327/62902719-c28c5e80-bd60-11e9-918f-2ba42dbf07b3.png)

Wexond is very slow and consumes too much memory to run quickly and efficiently. It doesn't have too many features and isn't suitable for everyday use. On attached screenshot wexond uses almost 800mb of ram with only facebook opened.

**Comment by sentialx** [comment]
At first you didn't follow the bug template nor did not provide me useful info. Next thing is that it uses Chromium under the hood to render webpages so its RAM and CPU usage is comparable. Also, you opened an extremely unoptimized and memory hogging website such as Facebook and you claim "it's just only Facebook opened". From the screenshot you provided I'm almost sure there are other tabs open or Chrome extensions loaded. Closing this as invalid.

**Comment by ghost** [comment]
No wonder why in chrome facebook uses about 450mb. ¯\_(ツ)_/¯
