### ISSUE TITLE
If Wexond is a "privacy-focused" browser, why is Google the recommended search engine?

### ISSUE THREAD

**Issue by sweezyio** [wexond/browser-base#287]
**Is your feature request related to a problem? Please describe.**

If Wexond is a "privacy-focused" browser, then why would Google be the recommended search engine? Google collects so much data and makes money off of that data.

**Describe the solution you'd like**

I would like the recommended search engine to be changed to DuckDuckGo.

**Describe alternatives you've considered**

There is no alternative. If you don't use a Google account, they still collect data. If you use Incognito Mode, they still collect data. If you disable as many data collecting options in settings, they still collect data.

**Additional context**

As you can see at [TOSDR](https://github.com/tosdr/tosdr.org), [DuckDuckGo](https://tosdr.org/#duckduckgo) is a far superior search engine than [Google](https://tosdr.org/#google).

**Comment by sentialx** [comment]
You can always set the default search engine to DuckDuckGo in settings.

**Comment by sweezyio** [comment]
I understand that, however, in the `README` and on the Wexond website it claims that it is "privacy-focused". How can this be true if you are recommending a search engine that is the opposite?

**Comment by sentialx** [comment]
Hmm, I will consider changing the default search engine to DuckDuckGo.

**Comment by sweezyio** [comment]
Thank you.
