### ISSUE TITLE
My advice

### ISSUE THREAD

**Issue by yeningyuan08** [wexond/browser-base#288]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kierandrewett** [comment]
What?

**Comment by yeningyuan08** [comment]
My advice is:
1. Migrate to Python Language 
2.Support for multi-national languages
[learn me](https://github.com/yeningyuan)

**Comment by GamingGeek** [comment]
what

**Comment by kierandrewett** [comment]
congrats @yeningyuan08 you are now the lead dev have fun!!!111

**Comment by samollari** [comment]
The sarcasm is real
