### ISSUE TITLE
Add Open the previous close browser TAB when starting the browser

### ISSUE THREAD

**Issue by gitQqqHs** [wexond/browser-base#291]
in chrome setting and firefox:
On startup:
choose continue where you left off
![image](https://user-images.githubusercontent.com/26195745/63136606-65650700-c005-11e9-8e8d-eecb1bdad862.png)

**Comment by gitQqqHs** [comment]
Every time you start the browser, you can start from the last browsing state

**Comment by sentialx** [comment]
Merging into #172
