### ISSUE TITLE
Pinned application tab

### ISSUE THREAD

**Issue by ctreadw6** [wexond/browser-base#296]
**Is your feature request related to a problem? Please describe.**
Pinning an application tab does not persist when relaunching.

**Describe the solution you'd like**
If you pin an captured application tab, ideally it would be recaptured when Wexond starts again, or launched and captured if it is not running.

Example steps:
Capture Discord application in a tab and pin it.
Close Wexond and release the application window.
Open Wexond.
If the pinned process is running, recaptured the window
else launch a new instance and capture the window.

**Describe alternatives you've considered**

**Additional context**
It will be difficult to determine whether a ProcessWindow is one that was pinned. You can not rely on the Window Title being the same or for a process to only have one window. It might be necessary to have the user enter additional information when pinning an application window, such as:
Command line args the app was launched with for if the process was not already running,
Window Title filter to match against (for process that have multiple windows).

**Comment by sentialx** [comment]
Closing since Multrin has been removed due to instability issues.
