### ISSUE TITLE
Bookmarks won't delete or add correctly.

### ISSUE THREAD

**Issue by mbouli** [wexond/browser-base#298]
**Bug description**
Bookmarks wont appear (unless you relaunch the app) or delete. If u delete them, they are deleted until you open the app again.

**To Reproduce**
Just add and remove bookmarks and quit the app and they won't be deleted.

**Expected behavior**
The bookmarks are meant to be deleted and the bookmarks are meant to be added when you click the star and not when you have to quit it.

**Details:**
 - Operating System: macOS: High Sierra 10.13.6
 - Wexond version: 3.0.1
 - Last known working Wexond version: This is my first time using Wexond.

**Comment by sentialx** [comment]
Unfortunately I can't reproduce this issue. Everything works fine to me.

**Comment by mbouli** [comment]
hmm okay so i also cloned the github repo and used it, and both have the glitch, maybe u need to have both? i'm not sure

**Comment by mbouli** [comment]
also, could u just lmk if there is a way in the code or in my file system i could delete the bookmarks?

**Comment by sentialx** [comment]
Try deleting `~/.wexond/storage/bookmarks.db`.

**Comment by mbouli** [comment]
thank u so much haha
