### ISSUE TITLE
Error while running command yarn run watch:app

### ISSUE THREAD

**Issue by ashishdoneriya** [wexond/browser-base#31]
ERROR in ./src/components/AddressBar/index.jsx
Module not found: Error: Can't resolve '../../defaults/wexond-urls' in '/home/impadmin/projects/wexond/src/components/AddressBar'
 @ ./src/components/AddressBar/index.jsx 3:0-52
 @ ./src/components/Bar/index.jsx
 @ ./src/components/App/index.jsx
 @ ./src/bootstrap.jsx

ERROR in ./src/components/Tab/index.jsx
Module not found: Error: Can't resolve '../../defaults/wexond-urls' in '/home/impadmin/projects/wexond/src/components/Tab'
 @ ./src/components/Tab/index.jsx 10:0-52
 @ ./src/components/Tabs/index.jsx
 @ ./src/components/App/index.jsx
 @ ./src/bootstrap.jsx

ERROR in ./node_modules/css-loader?{"sourceMap":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./src/app.scss
Module not found: Error: Can't resolve './images/Bar/wexond.png' in '/home/impadmin/projects/wexond/src'
 @ ./node_modules/css-loader?{"sourceMap":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./src/app.scss 6:8049-8083
 @ ./src/app.scss
 @ ./src/bootstrap.jsx

**Comment by sentialx** [comment]
Please use our issue creating guidelines. On what OS are you running Wexond? Which version?

**Comment by ashishdoneriya** [comment]
Ubuntu 14.04

**Comment by zjfjiayou** [comment]
On MAC OS, the same problem happens when compile

**Comment by vviikk** [comment]
Well that file seems to be missing. There is no `wexond-urls` script anywhere.

**Comment by sentialx** [comment]
Ok thanks, I will see that.

**Comment by sentialx** [comment]
Fixed by commit a2170e2.
