### ISSUE TITLE
White Screen of Death?

### ISSUE THREAD

**Issue by ghost** [wexond/browser-base#313]
**Bug description**
Every time I go into the "Address Bar" settings, a white screen appears and requires a close of the browser to fix.

**To Reproduce**
1. Open Wexond
2. Go to Settings
3. Open Address Bar settings

**Expected behavior**
The address bar settings were supposed to appear.

**Screenshots**
Just a white screen, should be obvious.

**Details:**
 - Operating System: Windows 10 (x64; Insider; Version 1903)
 - Wexond version: 3.1.0
 - Last known working Wexond version: 3.0.1

**Comment by sentialx** [comment]
Please show me your `~/.wexond/settings.json` file and try opening dev tools with `Ctrl+Shift+F12` while the error occurs.

**Comment by ghost** [comment]
No problem.

**Comment by ghost** [comment]
This is the `.wexond/settings.json` file:

```{"darkTheme":false,"shield":true,"multrin":true,"animations":true,"overlayBookmarks":true,"suggestions":true,"searchEngines":[],"searchEngine":-1,"startupBehavior":{"type":"continue"},"version":"3.1.0"}```

This is the development tools prompt in the settings in Wexond (*it's a GIF, so click on it to view it*):

![ezgif com-optimize](https://user-images.githubusercontent.com/53713662/64071269-061c1d80-ccba-11e9-9edf-b851ce7de7cb.gif)

**Comment by sentialx** [comment]
I don't know how is it possible you have `searchEngine` in `settings.json` set to -1. Also, I've been testing removing `.wexond`, installing 3.0.1 and upgrading to 3.1.0 and everything worked fine. So you may want to just set the `searchEngine` field to 0 instead of -1 or just to remove `settings.json`.

**Comment by ghost** [comment]
Very peculiar, but thank you for the prompt response!

**Comment by xylobol** [comment]
This seems to be a really strange bug-- I've just encountered it on Windows 10. The steps @sentialx posted fixed it, but this shouldn't really be possible in the first place. I'm going to play around later to see what causes this.

**Comment by sentialx** [comment]
I think I've fixed it recently. It happened when changing the search engine.
