### ISSUE TITLE
Add CORS

### ISSUE THREAD

**Issue by BlobCodes** [wexond/browser-base#317]
**Is your feature request related to a problem? Please describe.**
Most modern browsers check if the browser is allowed to make a request by sending a CORS preflight request. Wexond however (like many smaller browsers, e.g. KDE Falkon) does not do this. This is a security flaw which can be used to steal sessions, read user information, etc.

**Describe the solution you'd like**
Disabling CORS can be very helpful for developers like myself, so I'd suggest adding a (developer?) setting "Disable CORS" and enabling CORS by default.

**Describe alternatives you've considered**
For example in chromium, CORS is enabled by default but can be disabled via the command line (chromium --disable-web-security) or extensions. Wexond could implement CORS and wait for someone to create an extension.

**Additional context**
Here I have created a simple html file showing that CORS is in fact not working, please execute it in a major browser (edge/chromium/firefox) and afterwards compare it with wexond:
[test.tar.gz](https://github.com/wexond/desktop/files/3563633/test.tar.gz)
(The test requests google.com and adds it to the body's innerHTML, which should not be possible!)

**Comment by sentialx** [comment]
I think I can close this issue, since the Electron team says that's an expected behavior.
