### ISSUE TITLE
Open downloaded file when clicking on it

### ISSUE THREAD

**Issue by BlobCodes** [wexond/browser-base#321]
**Is your feature request related to a problem? Please describe.**
After downloading a file in wexond, I'm used from other browsers to click on the downloaded file to open it. Wexond does not do this and I think adding it would enchance the user experience.

**Describe the solution you'd like**
When clicking on a downloaded file in the "Downloads" section of the new tab page, it executes (maybe showing a modal asking what program to open it with like in firefox).

**Describe alternatives you've considered**
When clicking on a downloaded file in the "Downloads" section of the new tag page, it brings you to the downloads menu, where you can open it as well as do other stuff with it.

**Additional context**
None.

**Comment by sentialx** [comment]
That's weird, because it's working for me... What OS do you have?

**Comment by BlobCodes** [comment]
I'm using the Wexond 3.1.0.1342 Appimage on Manjaro Linux (KDE) 18.04

**Comment by BlobCodes** [comment]
I just opened wexond from the command line to see if it shows any helpful information - and it did!
Whenever I clicked on the downloaded (.zip) file, the following was shown on the console:
```
xdg-open -- opens a file or URL in the user's preferred
   application

Synopsis

   xdg-open { file | URL }

   xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.
```

Screenshot:
![click_download](https://user-images.githubusercontent.com/14961554/64131075-8e87e480-cdc6-11e9-9b7e-87206364f045.png)

**Comment by sentialx** [comment]
Maybe your OS doesn't recognize .zip?

**Comment by BlobCodes** [comment]
I habe multiple zip readers, that shouldn't be the problem. Also I think it didn't even work with pictures..

I'll try opening the zip with xdg-open directly from the command line when I'm back home.

**Comment by BlobCodes** [comment]
`xdg-open some.zip` totally works..
Maybe wexond calls the method wrongly?

**Comment by sentialx** [comment]
@BlobCodes Does it work for you on `v4.0.0-nightly.10`?

**Comment by BlobCodes** [comment]
> @BlobCodes Does it work for you on `v4.0.0-nightly.10`?

@sentialx Yes, works!

**Comment by BlobCodes** [comment]
I think this can be closed then.
