### ISSUE TITLE
After importing bookmarks browser is unusable

### ISSUE THREAD

**Issue by zderi** [wexond/browser-base#325]
**Bug description**
After importing bookmarks from html file (exported from Firefox) browser window becomes white and totaly unusable. After ending process in task manager and restarting browser it's still the same. 

**To Reproduce**
Try to import exported html bookmark file from Firefox to Wexond.

**Expected behavior**
Selecting and editing bookmarks as usual.

**Screenshots**
![wexond_bug](https://user-images.githubusercontent.com/16637746/64485786-0f126f00-d225-11e9-90e4-45606afb2c5a.PNG)

**Details:**
 - Operating System: Windows 7 x64
 - Wexond version: 3.1.0
 - Last known working Wexond version: n/a

**Additional context**
This is first Wexond version I try to use.

**Comment by sentialx** [comment]
Hi @zderi, sorry for the late response. As far as I know, Firefox doesn't use Netscape formatted bookmarks like Chromium and that's why it's crashing. If it's still crashing, please remove `~/.wexond/storage` folder.

**Comment by sentialx** [comment]
@zderi Could you provide me an example HTML file exported by Firefox?

**Comment by BlobCodes** [comment]
@sentialx Here you go!
[bookmarks.html.zip](https://github.com/wexond/desktop/files/3923661/bookmarks.html.zip)
