### ISSUE TITLE
How to access tab groups in latest version?

### ISSUE THREAD

**Issue by ptrwtts** [wexond/browser-base#338]
I just ran locally, and can't seem to find the tab group functionality. Is it gone, or in the process of redesign?

**Comment by sentialx** [comment]
Tab groups aren't implemented yet on `master`.

**Comment by sentialx** [comment]
@ptrwtts Now you can create tab groups via context menu.
![image](https://user-images.githubusercontent.com/11065386/69015190-f4314900-0991-11ea-95bf-7c1332ffcbf7.png)
If you want to customize your tab group, you can click on the circle next to the tabs.
![image](https://user-images.githubusercontent.com/11065386/69015202-0d39fa00-0992-11ea-91c9-b2fb0d17e91a.png)
