### ISSUE TITLE
Calculate tab background color from favicon if no color is given

### ISSUE THREAD

**Issue by BlobCodes** [wexond/browser-base#351]
**Is your feature request related to a problem? Please describe.**
The browser is not colorful enough :rainbow: .

**Describe the solution you'd like**
When a website gives no color in a manifest.json, tabs currently use the default color, but instead we could use the color of the favicon to make wexond more colorful :rainbow: .
Such an implementation can be seen in the vivaldi browser.

**Describe alternatives you've considered**
None.

**Additional context**
Here is how vivaldi generates the colors from the favicons:
![3fvnat](https://user-images.githubusercontent.com/14961554/68544265-987b2480-03c1-11ea-8b90-99f765bdcca7.gif)

**Comment by sentialx** [comment]
It does calculate the favicon vibrant color, however there are issues with JIMP import in node-vibrant https://github.com/akfish/node-vibrant/pull/102

**Comment by BlobCodes** [comment]
Oh I didn't know that. Sorry :D
