### ISSUE TITLE
Add (system) notification on file download showing current progress of download

### ISSUE THREAD

**Issue by BlobCodes** [wexond/browser-base#364]
**Is your feature request related to a problem? Please describe.**
In the current version of Wexond, I don't receive any feedback when a page downloads something.
However, I'd like receiving such a feedback.

**Describe the solution you'd like**
When downloading something, a persistent notification shows up, showing the current progress in a progress bar. When the download is finished, it does not become persistent anymore and renames it's title so one can see that the download was finished.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by sentialx** [comment]
I plan to make a downloads popup like in Firefox (obviously the design will be different)
![image](https://user-images.githubusercontent.com/11065386/69444117-f90a4a00-0d4f-11ea-90f5-e14d00778688.png)

Later I will think of adding an option in settings to use Chrome-like bottom bar for downloads.

Regarding the downloads persistance, the download history should appear under the `wexond://downloads` page in the future.
