### ISSUE TITLE
Closing the last open tab causes it to still be active

### ISSUE THREAD

**Issue by BlobCodes** [wexond/browser-base#365]
**Bug description**
When closing the last tab in wexond, this tab is still active and can be used.

**To Reproduce**
Open one tab on any page. Close the tab.

**Expected behavior**
The currently open tab closes.

**Screenshots**
I'm currently writing this issue without an open tab:
![Screenshot_20191122_152921](https://user-images.githubusercontent.com/14961554/69433940-e3d7f000-0d3c-11ea-8b5a-90798c236899.png)

**Details:**
 - Operating System: Manjaro Linux
 - Wexond version: 4.0.0-nightly.9
 - Last known working Wexond version: 3.1.0

**Additional context**
None

**Comment by BlobCodes** [comment]
After reading the comment on #362 , I'm sure it's the same cause.

**Comment by sentialx** [comment]
Also, when closing the last tab, the current window should close.
