### ISSUE TITLE
Problem with electron-extensions

### ISSUE THREAD

**Issue by void8192** [wexond/browser-base#369]
**Bug description**
The `npm run dev` command fails with this error:
```
Error: Cannot find module 'electron-extensions/background-preload'
```
When I'm removing the lines with `electron-extensions` in `webpack.config.js` (lines 28-35), at first glance the error is fixed, but without do it, error is breaking the build process of `build/main.bundle.js`

**To Reproduce**
```sh
npm install
```
```sh
npm run dev
```

**Expected behavior**
I got this window by removing some lines in the webpack's config, but I think this is not very correct.
![image](https://user-images.githubusercontent.com/45062062/69982996-58314100-153e-11ea-8e1a-241b0662716a.png)

**Details:**
 - Operating System: macOS 10.14.1 (18B75)
 - Wexond version: 3.1.0
 - `electron-extensions` version: 5.0.2

**Additional context:**
Could this bug with https://github.com/sentialx/electron-extensions

**Comment by sentialx** [comment]
@MicrochipQ Try removing `node_modules` and reinstalling.

**Comment by void8192** [comment]
@sentialx I tried it two times

**Comment by sentialx** [comment]
@MicrochipQ Do you have an `electron-extensions` folder in `node_modules`?

**Comment by void8192** [comment]
@sentialx, Yes, I have it.
![image](https://user-images.githubusercontent.com/45062062/69987072-57e97380-1547-11ea-8e2c-21f9496ba557.png)

**Comment by sentialx** [comment]
@MicrochipQ Does the commit resolve the problem for you?

**Comment by void8192** [comment]
@sentialx Yeah, it works!
