### ISSUE TITLE
Problem with quick menu

### ISSUE THREAD

**Issue by void8192** [wexond/browser-base#371]
**Bug description**
The quick menu losing focus after any click.

**To Reproduce**
Open Wexond. Click on the hamburger. Press any button on it. Try clicking another button in the menu, but this button will not be clickable and you can drag the browser window through the menu.

**Expected behavior**
It should not lose focus.

**Screenshots**
![Screen Shot 2019-12-03 at 2 03 28 AM](https://user-images.githubusercontent.com/45062062/70005819-8b41f780-1573-11ea-87e1-d4aeadceb4f1.png)

**Details:**
 - Operating System: macOS 10.14.1 (18B75)
 - Wexond version: 3.1.0
 - Last known working Wexond version: undefined

**Additional context**
This bug may be work on macOS only.
[Video](https://youtu.be/hz4jRQjaRK4)

**Comment by sentialx** [comment]
@MicrochipQ I noticed you have problems with dragging when changing the BrowserViews. It's related to https://github.com/electron/electron/issues/20926. Try resizing the window to make dragging work again.

**Comment by void8192** [comment]
@sentialx Yes, this fix is working.

**Comment by sentialx** [comment]
I was able to find a workaround for dragging the window by increasing the window height by 1 and restoring it to the original size. It may be a bit ugly but it works.

**Comment by void8192** [comment]
I noticed here, if I move the tabs, then the title bar becomes non-draggable. But when I switch to the previous tab, the title works.

**Comment by sentialx** [comment]
Did you try it on this commit https://github.com/wexond/desktop/commit/79104bcc887b0906a7791753b5d4e85c8bba6201?

**Comment by void8192** [comment]
I applied this commit, and the dragging of the title-bar and tabs is working.
