### ISSUE TITLE
Extensions don't work, clicking on the articles doesn't do anything.

### ISSUE THREAD

**Issue by DiegoMagdaleno** [wexond/browser-base#386]
**Bug description**

- When you go to extensions tab, nothing shows, just a not found.
- Clicking on articles does nothing
**To Reproduce**

- Go to the hamburger menu, click it and then click extensions.
- Open the browser and try to click any article
**Expected behavior**

- The extensions page to show, or the store
- The articles to redirect me to an specific web page 

**Screenshots**

https://i.imgur.com/U3oLTMh.png

**Details:**
 - Operating System: Darwin 19.3.0 + Aqua (macOS 10.15.3 Catalina) 
 - Wexond version: 4.0.0 beta 2
 - Last known working Wexond version: None/Unknown 

**Additional context**

**Comment by sentialx** [comment]
If you just want to install an extension, go to chrome web store. There's no extensions manager though

**Comment by sentialx** [comment]
The rest is fixed, so I'll just merge this issue into #252
