### ISSUE TITLE
Updating @cliqz/adblocker to 1.6.x might require internal changes

### ISSUE THREAD

**Issue by remusao** [wexond/browser-base#387]
Hey,

I released `@cliqz/adblocker` v1.6.x today and I wanted to give you a heads-up that it might require some changes in Wexond since I noticed you rely on internal APIs which have been removed. In particular:

* The preload script bundle is now under: `node_modules/@cliqz/adblocker-electron-preload/dist/preload.cjs.js` instead of `node_modules/@cliqz/adblocker-electron/dist/cjs/preload.js`.
* The blocker instance does not have `onBeforeRequest` and `onHeadersReceived` methods anymore (we could still access them differently though).

Regarding the last point, I would be happy to upstream improvements to the library so that you can simply call `engine.enableBlockingInSession(ses)` and have everything working as of now. Do you know if there are still blockers for that to happen? I see that Wexond initializes the webRequest listeners and preload script explicitly, but I am unsure if this is still required with latest version of `@cliqz/adblocker`.

Best,

**Comment by sentialx** [comment]
Hi,
I had to use `onBeforeRequest` etc. on my own, since Electron doesn't support multiple `webRequest` handlers. But I'm using a workaround package https://www.npmjs.com/package/electron-better-web-request in which the method `addListener` returns the listener data used later for removing the exact listener.

**Comment by remusao** [comment]
I see... I will look into it and see if `@cliqz/adblocker-electron` can be improved to handle this scenario as well. Thanks for clarifying.
