### ISSUE TITLE
support for legacy machines

### ISSUE THREAD

**Issue by andika207** [wexond/browser-base#393]
nice browser but it doesn't support Windows XP.
hope you fix this issue.

**Comment by sentialx** [comment]
Unfortunately, there is nothing I can do about this issue. Chromium has dropped support for Windows XP.

**Comment by andika207** [comment]
@sentialx I know 2 browsers compatible with XP that are based on chromium and up to date.. 7x version.
if you don't support XP it's because you don't want.

**Comment by sentialx** [comment]
@andika207 What are those 2 browsers?

**Comment by andika207** [comment]
@sentialx I said 2 but there are few more... just an example 

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/fT80L58T/screenshot-3.png' border='0' alt='screenshot-3'/></a>

**Comment by sentialx** [comment]
@andika207 I can't seem to find the "ChromeCore" browser. Without basically rewriting core parts of Chromium it is not possible to support Windows XP and also modifying Chromium requires modifying Electron, but I don't have enough knowledge to do that. But if you think that's super easy, then go ahead and create a Pull Request!

**Comment by andika207** [comment]
@sentialx that probably is the main headache because Electron doesn't support XP.
I don't know why some developers dropped XP support so soon back in 2014 because XP was still getting official updates till april 2019 so it actually is 8 months older than W7 and as you know XP is not from 2001 because SP3 came out in 2008.

**Comment by sentialx** [comment]
There's a very good reason why they dropped the support. XP is extremely insecure and with many security holes operating system.

**Comment by andika207** [comment]
@sentialx I have read somewhere that it's possible to get Electron to work for XP @weolar you can have a look at this profile https://github.com/weolar/miniblink49 

as for the chromecore browser this is the main site http://b.cqttech.com/
if you want to install it and prevent the typical ''junkware'' just uncheck the boxes.

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/d0BbM7LW/screenshot-3.png' border='0' alt='screenshot-3'/></a>

**Comment by weolar** [comment]
yes, I get Electron5.0 and chromium75 to work for XP.

**Comment by sentialx** [comment]
Electron 5 soon won't be supported and I'm targetting to use the latest possible Electron/Chromium version.

**Comment by weolar** [comment]
let the latest Electron to work for XP is possible, but need 2 or 3 week workload

**Comment by sentialx** [comment]
Completely not worth supporting an obsolete and deprecated operating system.

**Comment by andika207** [comment]
@weolar hats off, you must be a really good and experienced browser developer.
as I said since the beginning  it's a matter of will even if Blink engine does not support XP anymore.
