### ISSUE TITLE
Google Sign in

### ISSUE THREAD

**Issue by davidraywilson** [wexond/browser-base#424]
I'm not able to log in to my Google account through Wexond. Google is giving me the following message:

![Annotation 2020-03-31 194805](https://user-images.githubusercontent.com/6796060/78088027-93c30700-7388-11ea-85e9-8e5308cd2588.png)

This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

**Comment by sentialx** [comment]
Which version?

**Comment by davidraywilson** [comment]
I was on 4.0.0-nightly.40 when I posted this but I just tried it on 5.0.0-nightly.2 and got the same message.

**Comment by BlobCodes** [comment]
@davidraywilson Had the same issue and found a fix.
Changing the User-Agent to Firefox's works.

To do that, you need to edit this part of the src/main/view.ts file:
```js
//Before
    this.webContents.userAgent = this.webContents.userAgent
      .replace(/ Wexond\\?.([^\s]+)/g, '')
      .replace(/ Electron\\?.([^\s]+)/g, '')
      .replace(/Chrome\\?.([^\s]+)/g, 'Chrome/80.0.3987.162');

//After
    this.webContents.userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0";
```

(I wanted to upload my build of wexond so you can test but GitHub only accepts files <10MB)

The best thing we can do right now is probably just wait :smile: 

(Got the solution from https://www.reddit.com/r/kde/comments/e7136e/google_bans_falkon_and_konqueror_browsers/faicv9g/)

**Comment by nabeelvalley** [comment]
I see this has been added to To-do, can I just go ahead and try to make a PR with this change as it looks like it hasn't been done as yet?

**Comment by MrLuxuri** [comment]
**_When will this issue be fixed?_**
