### ISSUE TITLE
Ability to mute audio from tabs

### ISSUE THREAD

**Issue by lukehaas** [wexond/browser-base#435]
Currently, if sound is coming from one tab it's not obvious which one it is. Also, it's currently not possible to mute a tab.

Solution: it would be good if tabs with audio had a symbol/icon to show which tab is currently playing sound. This sound icon could also be clicked to toggle the sound.

**Comment by BlobCodes** [comment]
@lukehaas It is possible.
Right click tab -> Mute tab
![Screenshot_20200425_164623](https://user-images.githubusercontent.com/14961554/80282914-657ce100-8714-11ea-99cc-1f3ea1e048b0.png)

**Comment by BlobCodes** [comment]
An "audio playing" indicator would actually be a good idea..
