### ISSUE TITLE
Active tab overlaps group indicator

### ISSUE THREAD

**Issue by BlobCodes** [wexond/browser-base#439]
**Bug description**
When selecting a tab, the group indicator under that tab is not shown.

**To Reproduce**
1. Create a group with a tab
2. Select the tab

**Expected behavior**
The group indicator should stay where it was.

**Screenshots**
![Screenshot_20200425_145643](https://user-images.githubusercontent.com/14961554/80280582-327f2100-8705-11ea-9795-debaf7dd9b9c.png)

**Details:**
 - Operating System: OpenSUSE Tumbleweed
 - Wexond version: 5.0.0-nightly.10
 - Last known working Wexond version: 4.0.0-beta.4

**Additional context**
None

**Comment by sentialx** [comment]
Actually, that was expected. The group line is behind the selected tab.

**Comment by BlobCodes** [comment]
Oh okay.. but when a selected tab is at the border of a group, it looks like it's not in the group.
![Screenshot_20200425_163408](https://user-images.githubusercontent.com/14961554/80282604-9fe57e80-8712-11ea-9fba-83ecc39484b7.png)

**Comment by BlobCodes** [comment]
I would suggest something like this:
![Screenshot_20200425_163408](https://user-images.githubusercontent.com/14961554/80282772-9a3c6880-8713-11ea-9c8f-97175115825f.png)
