### ISSUE TITLE
Import bookmarks function does not work

### ISSUE THREAD

**Issue by Vicente015** [wexond/browser-base#487]
**Bug description**
I am trying to import my Opera bookmarks to Wexond but it doesn't work, I select the file but nothing matters.

Also, I added a bookmark to this browser to later export it, and then I deleted it and tried to import it to see if it was an Opera bug, but it still fails.

**To Reproduce**
1. Add a bookmark to Wexond.
2. Export the bookmarks.
3. Remove all bookmarks.
4. Import bookmarks from the file that was previously exported.

**Expected behavior**
I hoped the bookmarks would be imported successfully and appear.

**Screenshots**

**Details:**
 - Operating System: Windows 10 Home, Version: 1903
 - Wexond version: 5.0.1
 - Last known working Wexond version: I don't know

**Additional context**
![iLCu1fEwmy](https://user-images.githubusercontent.com/33096355/84602418-29960a80-ae7f-11ea-9e4b-6ccf3463a70d.gif)

**Comment by xnerhu** [comment]
Wexond at this point doesn't support importing bookmarks and history from other browsers. However we plan to make it in `6.0.0`.

**Comment by Vicente015** [comment]
Ok, thanks

**Comment by sentialx** [comment]
@xnerhu lol what? importing and exporting bookmarks is a thing and it looks clearly like a bug.

**Comment by ScottWallace** [comment]
The fix here is to change `/src/main/services/storage.ts` from this:

`import parse from 'node-bookmarks-parser';`

to this:

`import * as parse from 'node-bookmarks-parser';`

Can't say for sure, seems to not have been able to properly find the default function. First tried setting `"esModuleInterop": true` in `tsconfig.json`, but that created far more problems that it fixed. Finally found the above, works great.

Source:
[https://github.com/iamkun/dayjs/issues/475#issuecomment-460660048](https://github.com/iamkun/dayjs/issues/475#issuecomment-460660048)
