### ISSUE TITLE
Clear storage from one tab

### ISSUE THREAD

**Issue by arlogilbert** [wexond/browser-base#516]
I'm not sure whether this is a feature request or a help request, but I need to clear the cookies and storage from one of the tabs but not the others. It appears that all tabs share a single session, so when I clear the cookies using the this.webContents.session.clearStorageData, all tabs are cleared.

Is there a way to clear the cookies and storage only for a single tab?

**Comment by sentialx** [comment]
It's impossible with the current architecture. Each tab would need to have a separate Session.
