### ISSUE TITLE
Does not work with proxychains

### ISSUE THREAD

**Issue by killerdevildog11** [wexond/browser-base#517]
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
Trace/breakpoint trap (core dumped)

I am using ubuntu 20, and proxychains

**Comment by sentialx** [comment]
idk what this issue is about. Could you describe it more precisely? How are you loading proxychains into wexond etc.?
