### ISSUE TITLE
Unable to manage extensions

### ISSUE THREAD

**Issue by moeenio** [wexond/browser-base#519]
**Bug description**
I installed the latest wexond over an older version. When I click the "extensions" item in the menu it just redirects me to the chrome web store, while clicking the extensions icon on the left in the settings shows a "Your file was not found. It may have been moved or deleted." error. Cleaning the Application Support/wexond directory didn't help (i thought it could be incompatibility with the older version's profile?)

**Expected behavior**
A page to manage extensions should show.

**Details:**
 - Operating System: macOS 10.11.6
 - Wexond version: 5.1.0
 - Last known working Wexond version: n/a

**Comment by sentialx** [comment]
There is no extensions manager at the moment. It should redirect to chrome webstore.

**Comment by moeenio** [comment]
So how do you uninstall'extensions, deleting the file manually?

**Comment by sentialx** [comment]
Currently yes

**Comment by sentialx** [comment]
Merging into #252
