### ISSUE TITLE
How to bring the address bar in Compact mode?

### ISSUE THREAD

**Issue by moeenio** [wexond/browser-base#520]
It may sound weird but I don't understand how I am supposed to bring back the URL bar after entering a URL or navigating to a page. Sometimes clicking the tab seems to do it, sometimes it shows when switching windows... I think an obvious button would be great.

**Comment by moeenio** [comment]
Might just be bugs specific to me tho, but it could still be made more obvious how to show the address bar.

**Comment by sentialx** [comment]
Clicking on the selected tab should show the address bar.

**Comment by moeenio** [comment]
Sometimes, it doesn't.

**Comment by Madis0** [comment]
To me it shows the full new tab overlay, not just the address bar. 
Not specifically bad, but slightly confusing - maybe make some of the area transparent to show it is an overlay?

**Comment by Madis0** [comment]
To me it seems to show a new tab overlay instead, perhaps add some transparency to highlight the fact that it is an overlay?
