### ISSUE TITLE
import { Dialog } from '.';  Dialog in which file

### ISSUE THREAD

**Issue by fulus06** [wexond/browser-base#536]
![image](https://user-images.githubusercontent.com/12890684/96677048-5c0dc200-13a1-11eb-81be-0c34fb3b0627.png)

**Comment by sentialx** [comment]
`.` means `index.ts` file in the current folder.

**Comment by fulus06** [comment]
not found `index.ts` or `class Dialog ` in the current folder.
![image](https://user-images.githubusercontent.com/12890684/96723749-8b442380-13e1-11eb-8410-26b650a61103.png)

**Comment by sentialx** [comment]
or maybe dialog.ts

**Comment by fulus06** [comment]
not find class Dialog in project
