### ISSUE TITLE
Doesnot open on Windows

### ISSUE THREAD

**Issue by shalva97** [wexond/browser-base#538]
**Bug description**
Downloaded from website, installed but when i open it there is black screen and about 5 seconds it closes

**To Reproduce**
 install on Windows 10 and see if it opens? this seems to be too hard to miss, because other versions also do not work, tried few versions until 4.0.0 and none worked
**Expected behavior**
It should open

**Screenshots**

**Details:**
 - Operating System: Windows 10
 - Wexond version: 5.1.0 and also few older versions
 - Last known working Wexond version: not much time to find working version

**Additional context**

**Comment by shalva97** [comment]
Hello?

**Comment by sentialx** [comment]
I can't reproduce

**Comment by shalva97** [comment]
so how can I troubleshoot it?

**Comment by sentialx** [comment]
Do you have any antivirus?

**Comment by shalva97** [comment]
Just Windows Defender. but it doesnot seem to be doing anything...
