### ISSUE TITLE
Nah, Nothin

### ISSUE THREAD

**Issue by nxvvvv** [wexond/browser-base#542]
### ONE PROOF OF THAT IS: THERE IS AN ERROR IN WHICH WHEN I CLICK EXTENSIONS IN MIDORI BROWSER, IT SHOWS THIS ERROR: 
![image](https://user-images.githubusercontent.com/34748927/102960530-25bb0300-4508-11eb-8301-d6477290f7a1.png)

### IT SHOWS THE SAME ERROR IN WEXOND:
![image](https://user-images.githubusercontent.com/34748927/102960707-8c402100-4508-11eb-85ed-20a471fe61e4.png)

### ITS OK IF THEY HAD GIVEN CREDITS TO MIDORI AND IF THEY HAD SAID THAT THIS BROWSER IS JUST A RENAMED VERSION OF MIDORI, BUT NO, THEY WANT TO SHOW OFF BY COPY-PASTING SOMETHING SOMEONE MADE AND SAYING THAT THEY HAVE WORKED REAL HARD TO MAKE THIS SO PLEASE DONATE AND HELP US.

**Comment by nxvvvv** [comment]
### WHAT THE ...... 
![image](https://user-images.githubusercontent.com/34748927/102961088-6f581d80-4509-11eb-9984-2be0bd4c45a5.png)

**Comment by nxvvvv** [comment]
> ### WHAT THE ......
> ![image](https://user-images.githubusercontent.com/34748927/102961088-6f581d80-4509-11eb-9984-2be0bd4c45a5.png)

HEAVY DEVELOPEMENT?? ITS DONE BY MIDORI TEAM. LIARS

**Comment by nxvvvv** [comment]
### IF NO ONE TRUST ME, THEN GO TO OFFICIAL MIDORI WEBSITE AND INSTALL IT. THEN COMPARE IT SIDE BY SIDE

**Comment by nxvvvv** [comment]
### THE THING I'M SAYING IS THAT, YOU CAN USE ANY OPEN SOURCE BROWSER CUZ THAT'S WHY THEY'RE OPEN SOURCED, BUT YOU WILL HAVE TO GIVE CREDITS TO THE "ORIGINAL" DEVS. BUT YOU WON'T DO THAT CUZ THIS BROWSER IS THE SAME AS MIDORI AND PEOPLE WILL RECOGNISE IT.

**Comment by sentialx** [comment]
nice troll

**Comment by xnerhu** [comment]
xd

**Comment by ricardoGonzf** [comment]
U dum lol
The first commit in this repo was in 2017* and the first midori commit was 3 moths ago lol
*Also there was a browser that sentialx made long time ago that that browser is now wexond lol

**Comment by nxvvvv** [comment]
> U dum lol
> The first commit in this repo was in 2017* and the first midori commit was 3 moths ago lol
> *Also there was a browser that sentialx made long time ago that that browser is now wexond lol

I'm not dumb, you're dumb. Wexond first commit was at 2017. Midori's was at 2007. 
![image](https://user-images.githubusercontent.com/34748927/102994924-0a6ee880-4546-11eb-8cae-63cf78b1d4c0.png)

**Comment by nxvvvv** [comment]
Its not first commit, its first release. So commit will be way earlier than that
https://launchpad.net/midori/+series

**Comment by sentialx** [comment]
ok, look who is the copyright holder https://gitlab.com/midori-web/midori-desktop/-/blob/master/LICENSE#L655

**Comment by sentialx** [comment]
> THIS SO PLEASE DONATE AND HELP US.

they are not allowed to accept donations as per the PATENTS file in this repository.

**Comment by nxvvvv** [comment]
https://github.com/midori-browser What bout this?

**Comment by sentialx** [comment]
What

**Comment by nxvvvv** [comment]
License was taken 13 years ago

**Comment by sentialx** [comment]
The browser you just linked is the old version of midori based on GTK. Wexond is based on Electron.

**Comment by nxvvvv** [comment]
So how are you connected with the new midori?
@sentialx

**Comment by sentialx** [comment]
I'm not involved in Midori. They just forked my browser and changed branding as you described.

**Comment by nxvvvv** [comment]
oh! so the current gui is your idea?

**Comment by nxvvvv** [comment]
I thought it was their cuz they have been here for a long time

**Comment by nxvvvv** [comment]
If that's the case, then sorry for all this

**Comment by ricardoGonzf** [comment]
> > U dum lol
> > The first commit in this repo was in 2017* and the first midori commit was 3 moths ago lol
> > *Also there was a browser that sentialx made long time ago that that browser is now wexond lol
> 
> I'm not dumb, you're dumb. Wexond first commit was at 2017. Midori's was at 2007.
> ![image](https://user-images.githubusercontent.com/34748927/102994924-0a6ee880-4546-11eb-8cae-63cf78b1d4c0.png)

Haha, look midori was created at 2007 but the gui was not that good, so midori fork Wexond for better gui

Also like sentialx said https://gitlab.com/midori-web/midori-desktop/-/blob/master/LICENSE#L655 so please inform your self nex time

**Comment by javaarchive** [comment]
By your logic, you should also go complain the midori/wexond of chrome based on the waiting pages, though I do feel like part of the idea of Wexond is to look similar to chrome
and by the way over here it says "This Midori renovation uses Wexond as a base but little by little it will be integrating many new innovations, thanks to Mert Gör."
https://gitlab.com/midori-web/midori-desktop/-/tree/master

**Comment by nxvvvv** [comment]
Ok

**Comment by Genau6502** [comment]
You are brainwashed and frankly hilarious. You should become a comedian

**Comment by nxvvvv** [comment]
Bro. I admitted my mistake. Then why are you picking again?

**Comment by nxvvvv** [comment]
I understood what happened then why the hell are you saying this again

> If that's the case, then sorry for all this

I said sorry to them to then why are you starting all this again????
