### ISSUE TITLE
New title bar design idea (suggestion)

### ISSUE THREAD

**Issue by MrLuxuri** [wexond/browser-base#554]
The main part in a browser that attracts users and the part that needs to be more appealing is the title bar in the browser's UI. 
Today most of the browsers have their address bar on the bottom and they have the tabs on the top which is what today's browsers follow such as firefox, chrome, brave, vivaldi and etc.
![disable-chrome-new-theme](https://user-images.githubusercontent.com/71905307/107823549-02654500-6d4e-11eb-99b4-d465e683dc80.jpg)
But there is one browser that plays unique in the market and thats **Apple Safari**.
![Screen Shot 2021-02-12 at 3 57 21 PM](https://user-images.githubusercontent.com/71905307/107822748-9cc48900-6d4c-11eb-8d5d-0faf37c2f099.png)
![safarinew 0](https://user-images.githubusercontent.com/71905307/107823694-2de82f80-6d4e-11eb-94f5-1129cc9cae09.jpg)
A lot of users love safari's UI and the way it is. In safari, the Address bar is on **top** while it's tabs are on the bottom (All the way around). And the biggest advantage is that, it makes it look even more sleeker and rich-looking design. 
I am suggesting to move the tabs bellow the address bar, this will also avoid being together with the exit, minimising, and full screen button. This should be done in the full mode and on the compact mode, this will make the browser look sleek, clean and unique at the same time instead of having it like chrome and 90% of the other browsers. 

_If you don't understand or have doubts about anything, please feel free to comment bellow, i will reply asap_

**Comment by sentialx** [comment]
The main advantage of keeping tabs at the top is that when maximized, users generally tend to move cursor to the edge and just click on the tab.

**Comment by MrLuxuri** [comment]
> The main advantage of keeping tabs at the top is that when maximized, users generally tend to move cursor to the edge and just click on the tab.

@sentialx Well, while it is true, it really isn't an advantage instead, it just the way it functions when the tabs are on top. Keeping the tabs on the bottom simply avoid colliding with the exit, minimising, and full screen button as well as it makes the whole browser organized and look sleek. For, example, Safari works perfect when it's maximized and doesn't really have any problems having the tabs on the bottom.  

A lot of browsers today have simply been adapting chrome's "way" with minimal design changes. Safari's UI is the most beloved when it comes to apple users that is simply missed by windows 10 users as Safari isn't available for PC. Making the UI look safari-like instead of Chrome-like as usual will attract more users especially when PC users don't have safari, people who loves it's design will start using Wexond if it offers similar experience. This will in-directly help the browser grow significantly.
