### ISSUE TITLE
Cannot pull tabs out to their own window 

### ISSUE THREAD

**Issue by swiftaes** [wexond/browser-base#570]
**Is your feature request related to a problem? Please describe.**

It gets frustrating when I can't pull a tab out to its own window 
**Describe the solution you'd like**

To have the ability to pull out a tab shown in additional context
**Describe alternatives you've considered**

I have tried using the 3 dot menu to open a new window but its sort of clunky doing so
**Additional context**

https://streamable.com/1scewv 5s vid of what I can't do with Wexond

**Comment by sentialx** [comment]
Merging into #350
