### ISSUE TITLE
[issue] Can't import node module

### ISSUE THREAD

**Issue by MonkeyTiger** [wexond/browser-base#571]
I can't import node module like article-parser.

src/main/index.ts
import { extract } from 'article-parser';

I get this error.
extract is not function

So I tried to follow.
import * as extract from 'article-parser';
......
console.log(extract);

This is result of console.
{ isNightly: false, version: '6.0.0-nightly.2' }

Why can't import module? Please help me.

**Comment by sentialx** [comment]
I don't think this is an issue related with the browser.
