### ISSUE TITLE
Find workaround to hide <webview>.

### ISSUE THREAD

**Issue by sentialx** [wexond/browser-base#6]
Find another solution to hide <webview> without setting `display: none`.

**Comment by Sential** [comment]
Commit c1a1014 fixed it.

**Comment by sentialx** [comment]
Only changing opacity and height can hide it properly, but it lowers performance. Setting webview's display to none doesn't affect to performance, but it isn't working properly. See details in https://github.com/electron/electron/issues/8277.

**Comment by sentialx** [comment]
Closing this issue since the large amount of tabs lowers performance.
