### ISSUE TITLE
Clear All History DOESN'T work.

### ISSUE THREAD

**Issue by snaildos** [wexond/browser-base#613]
**Bug description**
Pressing clear all, doesn't work.

**To Reproduce**
Go to history, press clear all, then close and open wexond, the history is still there.

**Expected behavior**
History get's deleted
**Screenshots**

**Details:**
 - Operating System: Windows 10
 - Wexond version: Latest Beta
 - Last known working Wexond version: Unkown

**Additional context**

**Comment by sreco** [comment]
Clear all history, now work!
